### ISSUE TITLE
System.Exception: Deployment failed: Windows cannot remove Microsoft.MinecraftUWP_1.18.2.0_x64__8wekyb3d8bbwe because the PreserveApplicationData flag can only be used on a package that was deployed in development mode.

### ISSUE THREAD

**Issue by chiayunhau** [BedrockLauncher/BedrockLauncher#129]
Fulll error:

`Application Starting...
Checking for updates
Current tag: 0.0.2.6
Latest tag: 0.0.2.1
Removing package: Microsoft.MinecraftUWP_1.18.2.0_x64__8wekyb3d8bbwe
Deployment failed: Windows cannot remove Microsoft.MinecraftUWP_1.18.2.0_x64__8wekyb3d8bbwe because the PreserveApplicationData flag can only be used on a package that was deployed in development mode.
App launch failed:
System.Exception: Deployment failed: Windows cannot remove Microsoft.MinecraftUWP_1.18.2.0_x64__8wekyb3d8bbwe because the PreserveApplicationData flag can only be used on a package that was deployed in development mode.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 575
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<UnregisterPackages>d__26.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 525
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<Launch>d__19.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 276
Application Pre-Initalization Finished!
`

![image](https://user-images.githubusercontent.com/73814185/150623516-a4577ca6-8f5c-4aff-abde-cf0775ab6c5b.png)

**Comment by Rayth** [comment]
Did you have minecraft installed before installing launcher? If so, uninstall it through control panel first then use launcher

**Comment by Rayth** [comment]
backup your worlds first

**Comment by chiayunhau** [comment]
Thanks it worked
