### ISSUE TITLE
When it backups my files, it gives the following error:

### ISSUE THREAD

**Issue by mrpatches123** [BedrockLauncher/BedrockLauncher#134]
Error log:

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\mrpat\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\development_behavior_packs\Neutron Network GameTest systems\node_modules\stream-browserify\node_modules\readable-stream\lib\internal\streams\async_iterator.js'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at BedrockLauncher.ViewModels.GameManager.<Backup>g__RestoreCopy_Step|13_3(String from, String to) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 189
   at BedrockLauncher.ViewModels.GameManager.<Backup>g__RestoreCopy_Step|13_3(String from, String to) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 196
   at BedrockLauncher.ViewModels.GameManager.<Backup>g__RestoreCopy_Step|13_3(String from, String to) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 196
   at BedrockLauncher.ViewModels.GameManager.<Backup>g__RestoreCopy_Step|13_3(String from, String to) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 196
   at BedrockLauncher.ViewModels.GameManager.<Backup>g__RestoreCopy_Step|13_3(String from, String to) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 196
   at BedrockLauncher.ViewModels.GameManager.<Backup>g__RestoreCopy_Step|13_3(String from, String to) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 196
   at BedrockLauncher.ViewModels.GameManager.<Backup>g__RestoreCopy_Step|13_3(String from, String to) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 196
   at BedrockLauncher.ViewModels.GameManager.<Backup>g__RestoreCopy_Step|13_3(String from, String to) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 196
   at BedrockLauncher.ViewModels.GameManager.<Backup>g__RestoreCopy_Step|13_3(String from, String to) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 196
   at BedrockLauncher.ViewModels.GameManager.<Backup>g__RestoreCopy_Step|13_3(String from, String to) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 196
   at BedrockLauncher.ViewModels.GameManager.<Backup>g__RestoreCopy|13_2(String from, String to) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 181
   at BedrockLauncher.ViewModels.GameManager.<>c.<Backup>b__13_0() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 138
```

**Comment by TresAbhi** [comment]
This is an issue with `Neutron Network Gametest...`'s node dependency `stream-browserify`. If you're developing the addon, remember to run `npm install` to install the dependencies before running Minecraft.
