### ISSUE TITLE
it says com.mojang is denied is that my fault or a bug

### ISSUE THREAD

**Issue by mrpatches123** [BedrockLauncher/BedrockLauncher#135]
System.IO.IOException: Access to the path 'C:\Users\mrpat\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang' is denied.
   at BedrockLauncher.ViewModels.GameManager.<>c__DisplayClass23_0.<SetInstallationDataPath>b__0() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 462
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<SetInstallationDataPath>d__23.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 407
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<Launch>d__19.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 275

**Comment by Rayth** [comment]
Make sure you run launcher as administrator

**Comment by TresAbhi** [comment]
Please check out the FAQ on the [official website](https://bedrocklauncher.github.io/faq/) as it answers this exact question.
