### ISSUE TITLE
"Cannot create a file when that file already exists"

### ISSUE THREAD

**Issue by Scienceguy458** [BedrockLauncher/BedrockLauncher#189]
I tried playing Minecraft 1.16.100.4, and I got this error. I never played this update, and it says it cannot create a file when in exists. I cleared the versions folder except for 1.18.12.1.  It still gave me that error. This happened in 0.0.2.1 and 0.0.2.6.![75054e29-c07d-4f9b-9f4d-3c540a52a8ea](https://user-images.githubusercontent.com/99567833/163740813-af776647-f60b-4828-be39-14efd24a2223.png
[Log.txt](https://github.com/BedrockLauncher/BedrockLauncher/files/8503286/Log.txt)
)

**Comment by Rayth** [comment]
can you post the crash report and your log.txt file

**Comment by Rayth** [comment]
and confirm which version of the launcher you're on

**Comment by TheEpikBoi** [comment]
I guess you need to uninstall the Minecraft application first to fix this(don't forget to back up)

**Comment by Scienceguy458** [comment]
The launcher version is 0.0.2.1. I also tested this on 0.0.2.6

**Comment by Scienceguy458** [comment]
Log.txt:
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Version list local cache load failed:
System.IO.FileNotFoundException: Could not find file 'C:\Users\dflor\AppData\Roaming\.minecraft_bedrock\versions.json'.
File name: 'C:\Users\dflor\AppData\Roaming\.minecraft_bedrock\versions.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionJsonDb.ReadJson(String filePath) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:line 134
   at BedrockLauncher.Downloaders.VersionDownloader.LoadFromLocalCache(ObservableCollection`1 versions) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 130
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
Version list user cache load failed:
System.IO.FileNotFoundException: Could not find file 'C:\Users\dflor\AppData\Roaming\.minecraft_bedrock\local_versions.json'.
File name: 'C:\Users\dflor\AppData\Roaming\.minecraft_bedrock\local_versions.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionJsonDb.ReadJson(String filePath) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:line 134
   at BedrockLauncher.Downloaders.VersionDownloader.LoadFromUserCache(ObservableCollection`1 versions) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 109
Version list user cache load failed:
System.IO.FileNotFoundException: Could not find file 'C:\Users\dflor\AppData\Roaming\.minecraft_bedrock\local_versions.json'.
File name: 'C:\Users\dflor\AppData\Roaming\.minecraft_bedrock\local_versions.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionJsonDb.ReadJson(String filePath) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:line 134
   at BedrockLauncher.Downloaders.VersionDownloader.LoadFromUserCache(ObservableCollection`1 versions) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 109
Version list technical cache load failed:
System.IO.FileNotFoundException: Could not find file 'C:\Users\dflor\AppData\Roaming\.minecraft_bedrock\technical_local_versions.txt'.
File name: 'C:\Users\dflor\AppData\Roaming\.minecraft_bedrock\technical_local_versions.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionTextDb.Read(String filePath) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:line 51
   at BedrockLauncher.Downloaders.VersionDownloader.LoadFromTechCache() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 151
Moving backup Minecraft data to: C:\Users\dflor\AppData\Roaming\.minecraft_bedrock\installations\Scienceguy458\RecoveryData\packageData
Download start
Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/e7dc8885-57f5-4a53-b2fc-410b1a0eb5af?P1=1650267880&P2=404&P3=2&P4=FrHJoejFM6YlAIZyDJW3PT2CbGCmy2eNXGqVXOFwSL6AUzZTn0uXWdj2yysa6BvXkW%2bnjtuskBosUYGhyURY6w%3d%3d
Actual download started
Download complete
Extraction started

**Comment by Rayth** [comment]
Can you try the latest beta? https://github.com/BedrockLauncher/BedrockLauncher-Beta/releases/tag/2022.4.17.21

It looks like it's looking for a file "'C:\Users\dflor\AppData\Roaming.minecraft_bedrock\versions.json'" though when it should be "'C:\Users\dflor\AppData\Roaming\minecraft_bedrock\versions.json'"

**Comment by TresAbhi** [comment]
Closing due to inactivity
