### ISSUE TITLE
Clicking on the Articles in the News Page Makes the Launcher Crash

### ISSUE THREAD

**Issue by NT690** [BedrockLauncher/BedrockLauncher#204]
Here is the log 
```2022-05-06 22:34:29.1049|DEBUG||Version: 2022.4.17.20
2022-05-06 22:34:29.1515|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher.git
2022-05-06 22:34:29.1515|DEBUG||Git Branch: master
2022-05-06 22:34:29.1515|DEBUG||Git Commit: 9eec8df
2022-05-06 22:34:29.1515|DEBUG||Git Sha: 9eec8dfc49ceab583cddb3f991d8cece8bf5201b
2022-05-06 22:34:29.3888|DEBUG||Application Starting...
2022-05-06 22:34:29.6463|DEBUG||Application Initalization Started!
2022-05-06 22:34:29.6463|DEBUG||Application Initalization Finished!
2022-05-06 22:34:31.5150|DEBUG||Preparing Application...
2022-05-06 22:34:57.8236|DEBUG||Checking for updates
2022-05-06 22:34:59.1246|DEBUG||Current tag: 2022.4.17.20
2022-05-06 22:34:59.1246|DEBUG||Latest tag: 2022.4.17.21
2022-05-06 22:34:59.1246|DEBUG||New version available!
2022-05-06 22:34:59.1286|DEBUG||Preparing Application: DONE
2022-05-06 22:35:18.5396|DEBUG||System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'https://www.minecraft.net/article/taking-inventory--spyglass?ref=launcher' with working directory 'E:\Downloads\build'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at BedrockLauncher.Controls.Items.News.FeedItem_Offical.LoadArticle(NewsItem item) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Controls\Items\News\FeedItem_Offical.xaml.cs:line 32
   at BedrockLauncher.Controls.Items.News.FeedItem_Offical.FeedItemEntry_Click(Object sender, RoutedEventArgs e) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Controls\Items\News\FeedItem_Offical.xaml.cs:line 37
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by NT690** [comment]
https://user-images.githubusercontent.com/70166536/167240240-f69693d6-9175-4c96-a0e0-d9c3f686b109.mp4

Note that the "Bedrock Launcher has stopped working" window doesn't appear as i took a recording of the window, and that opens in a new window.

**Comment by Rayth** [comment]
Fixed
