### ISSUE TITLE
The "Official" Tab In the "News" Menu Fails to Load

### ISSUE THREAD

**Issue by NT690** [BedrockLauncher/BedrockLauncher#205]
![screenshot](https://user-images.githubusercontent.com/70166536/167241061-6ec69e3a-77c4-4b52-9a4c-a84a7efe1720.png)
There's also a spelling error (it's supposed to say try turning "_them_" not "the" back on)

**Comment by TresAbhi** [comment]
Can you provide a log?

**Comment by NT690** [comment]
```2022-05-09 17:33:28.9583|DEBUG||Version: 2022.4.17.20
2022-05-09 17:33:29.1087|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher.git
2022-05-09 17:33:29.1087|DEBUG||Git Branch: master
2022-05-09 17:33:29.1087|DEBUG||Git Commit: 9eec8df
2022-05-09 17:33:29.1087|DEBUG||Git Sha: 9eec8dfc49ceab583cddb3f991d8cece8bf5201b
2022-05-09 17:33:30.1119|DEBUG||Application Starting...
2022-05-09 17:33:30.6575|DEBUG||Application Initalization Started!
2022-05-09 17:33:30.6575|DEBUG||Application Initalization Finished!
2022-05-09 17:33:38.8109|DEBUG||Preparing Application...
2022-05-09 17:33:42.9239|DEBUG||System.Configuration.ConfigurationErrorsException: Failed to save settings: The configuration file has been changed by another program. (C:\Users\Dalima\AppData\Local\CarJem_Generations\BedrockLauncher_Url_ryyaqdpvs5kixbxzrpmzkxsdjawwkcj4\2022.4.17.20\user.config)
 ---> System.Configuration.ConfigurationErrorsException: The configuration file has been changed by another program. (C:\Users\Dalima\AppData\Local\CarJem_Generations\BedrockLauncher_Url_ryyaqdpvs5kixbxzrpmzkxsdjawwkcj4\2022.4.17.20\user.config)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.Configuration.SaveAsImpl(String filename, ConfigurationSaveMode saveMode, Boolean forceSaveAll)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at System.Configuration.ApplicationSettingsBase.Save()
   at BedrockLauncher.Localization.Language.LanguageManager.<SetLanguage>g__SetToDefaultLangauge|6_1() in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\modules\BedrockLauncher.Localization\Language\LanguageManager.cs:line 165
   at BedrockLauncher.Localization.Language.LanguageManager.SetLanguage(String language) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\modules\BedrockLauncher.Localization\Language\LanguageManager.cs:line 153
   at BedrockLauncher.Localization.Language.LanguageManager.Init() in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\modules\BedrockLauncher.Localization\Language\LanguageManager.cs:line 178
   at BedrockLauncher.Program.<>c.<<OnApplicationLoaded>b__3_0>d.MoveNext() in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Program.cs:line 54
--- End of stack trace from previous location ---
   at BedrockLauncher.ViewModels.MainViewModel.<>c__DisplayClass50_0.<<ShowWaitingDialog>b__0>d.MoveNext() in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\MainViewModel.cs:line 144
--- End of stack trace from previous location ---
   at BedrockLauncher.ViewModels.MainViewModel.ShowWaitingDialog(Func`1 action) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\MainViewModel.cs:line 141
   at BedrockLauncher.Program.OnApplicationLoaded() in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Program.cs:line 50
   at BedrockLauncher.MainWindow.Window_Initialized(Object sender, EventArgs e) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\MainWindow.xaml.cs:line 70
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Rayth** [comment]
Fixed in latest release
