### ISSUE TITLE
Crash when clicking on a link in the about section

### ISSUE THREAD

**Issue by Mcfly2340** [BedrockLauncher/BedrockLauncher#206]
the launcher crashes when you click on any link in the about section

**Comment by TresAbhi** [comment]
Can you provide a log?

**Comment by NT690** [comment]
not op but here's the log I get when i try

```2022-05-12 17:54:03.0685|DEBUG||Version: 2022.4.17.20
2022-05-12 17:54:03.1419|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher.git
2022-05-12 17:54:03.1419|DEBUG||Git Branch: master
2022-05-12 17:54:03.1419|DEBUG||Git Commit: 9eec8df
2022-05-12 17:54:03.1419|DEBUG||Git Sha: 9eec8dfc49ceab583cddb3f991d8cece8bf5201b
2022-05-12 17:54:19.3040|DEBUG||Application Starting...
2022-05-12 17:54:24.8514|DEBUG||Application Initalization Started!
2022-05-12 17:54:24.8514|DEBUG||Application Initalization Finished!
2022-05-12 17:54:32.7900|DEBUG||Preparing Application...
2022-05-12 17:55:02.4913|DEBUG||Checking for updates
2022-05-12 17:55:03.8415|DEBUG||Current tag: 2022.4.17.20
2022-05-12 17:55:03.8415|DEBUG||Latest tag: 2022.4.17.21
2022-05-12 17:55:03.8415|DEBUG||New version available!
2022-05-12 17:55:03.8415|DEBUG||Preparing Application: DONE
2022-05-12 17:55:19.5475|DEBUG||System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'https://www.minecraft.net/en-us/' with working directory 'E:\Downloads\build'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at BedrockLauncher.Pages.Settings.AboutPage.Button_Click(Object sender, RoutedEventArgs e) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Pages\Settings\AboutPage.xaml.cs:line 43
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by NT690** [comment]
I feel like this is somewhat related to #204, where it produces a similar result but with links on the news page. I think the issue has to do with the external links in general, and not specific parts.
