### ISSUE TITLE
App registration failed

### ISSUE THREAD

**Issue by DelofJ** [BedrockLauncher/BedrockLauncher#240]
Suite of [#39](https://github.com/BedrockLauncher/BedrockLauncher/issues/39)
The registration of Minecraft fails with old Betas of Minecraft
Here is a fresh crash report
```
2022-07-04 17:58:01.1818|DEBUG||Version: 2022.7.3.62
2022-07-04 17:58:01.2140|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher.git
2022-07-04 17:58:01.2140|DEBUG||Git Branch: lite
2022-07-04 17:58:01.2140|DEBUG||Git Commit: fd62b51
2022-07-04 17:58:01.2140|DEBUG||Git Sha: fd62b51344c76c59ce6db2f62cdf1c6b44634b52
2022-07-04 17:58:01.2140|DEBUG||Application Starting...
2022-07-04 17:58:01.3509|DEBUG||Application Initalization Started!
2022-07-04 17:58:01.3509|DEBUG||Application Initalization Finished!
2022-07-04 17:58:01.9485|DEBUG||Preparing Application...
2022-07-04 17:58:04.1055|DEBUG||Checking for updates
2022-07-04 17:58:04.2286|DEBUG||Check for updates failed
Error:Response status code does not indicate success: 403 (rate limit exceeded).
2022-07-04 17:58:04.2286|DEBUG||Preparing Application: DONE
2022-07-04 17:58:40.9218|DEBUG||Skipping package removal - same path: Microsoft.MinecraftUWP_1.19.202.0_x64__8wekyb3d8bbwe C:\Users\DelofJ\AppData\Roaming\.minecraft_bedrock\versions\Minecraft-61cab36e-3b4b-483c-9633-3915a3bd4f12
2022-07-04 17:58:40.9218|DEBUG||Registering package
2022-07-04 17:58:41.4004|DEBUG||Deployment done: Completed
2022-07-04 17:58:41.4015|DEBUG||App re-register done!
2022-07-04 17:58:42.0401|DEBUG||App launch finished!
2022-07-04 17:59:44.5944|DEBUG||Removing package: Microsoft.MinecraftUWP_1.19.202.0_x64__8wekyb3d8bbwe
2022-07-04 17:59:49.1343|DEBUG||Deployment done: Completed
2022-07-04 17:59:49.1343|DEBUG||Removal of package done: Microsoft.MinecraftUWP_1.19.202.0_x64__8wekyb3d8bbwe
2022-07-04 17:59:49.1368|DEBUG||Registering package
2022-07-04 17:59:53.1745|DEBUG||Deployment done: Completed
2022-07-04 17:59:53.1745|DEBUG||App re-register done!
2022-07-04 17:59:53.8633|DEBUG||App launch finished!
2022-07-04 18:00:47.3369|DEBUG||Removing package: Microsoft.MinecraftUWP_1.19.5.0_x64__8wekyb3d8bbwe
2022-07-04 18:00:50.9623|DEBUG||Deployment done: Completed
2022-07-04 18:00:50.9623|DEBUG||Removal of package done: Microsoft.MinecraftUWP_1.19.5.0_x64__8wekyb3d8bbwe
2022-07-04 18:00:50.9640|DEBUG||Registering package
2022-07-04 18:00:51.4592|DEBUG||Deployment failed: Le package Microsoft.MinecraftUWP_1.17.1023.0_x64__8wekyb3d8bbwe avec l'origine Windows Store ne peut pas être chargé latéralement ou installé à l'aide de l'option du mode développeur.
2022-07-04 18:00:51.4874|DEBUG||App registeration failed:
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Le package Microsoft.MinecraftUWP_1.17.1023.0_x64__8wekyb3d8bbwe avec l'origine Windows Store ne peut pas être chargé latéralement ou installé à l'aide de l'option du mode développeur.
 ---> System.Exception: Deployment failed: Le package Microsoft.MinecraftUWP_1.17.1023.0_x64__8wekyb3d8bbwe avec l'origine Windows Store ne peut pas être chargé latéralement ou installé à l'aide de l'option du mode développeur.
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 471
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 217
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 228
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 60
2022-07-04 18:06:44.1135|DEBUG||Registering package
2022-07-04 18:06:44.5862|DEBUG||Deployment failed: Le package Microsoft.MinecraftUWP_1.17.1023.0_x64__8wekyb3d8bbwe avec l'origine Windows Store ne peut pas être chargé latéralement ou installé à l'aide de l'option du mode développeur.
2022-07-04 18:06:44.5862|DEBUG||App registeration failed:
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Le package Microsoft.MinecraftUWP_1.17.1023.0_x64__8wekyb3d8bbwe avec l'origine Windows Store ne peut pas être chargé latéralement ou installé à l'aide de l'option du mode développeur.
 ---> System.Exception: Deployment failed: Le package Microsoft.MinecraftUWP_1.17.1023.0_x64__8wekyb3d8bbwe avec l'origine Windows Store ne peut pas être chargé latéralement ou installé à l'aide de l'option du mode développeur.
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 471
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 217
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 228
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 60
2022-07-04 18:06:55.8103|DEBUG||Registering package
2022-07-04 18:06:56.2626|DEBUG||Deployment failed: Le package Microsoft.MinecraftUWP_1.17.1023.0_x64__8wekyb3d8bbwe avec l'origine Windows Store ne peut pas être chargé latéralement ou installé à l'aide de l'option du mode développeur.
2022-07-04 18:06:56.2626|DEBUG||App registeration failed:
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Le package Microsoft.MinecraftUWP_1.17.1023.0_x64__8wekyb3d8bbwe avec l'origine Windows Store ne peut pas être chargé latéralement ou installé à l'aide de l'option du mode développeur.
 ---> System.Exception: Deployment failed: Le package Microsoft.MinecraftUWP_1.17.1023.0_x64__8wekyb3d8bbwe avec l'origine Windows Store ne peut pas être chargé latéralement ou installé à l'aide de l'option du mode développeur.
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 471
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 217
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 228
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\UserData\Source\visual_studio_repos\mc_repos\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 60

```

**Comment by Rayth** [comment]
Before I mark this as a valid issue I need to check:

- Do you have an active valid insider account that you've specified inside the launcher settings? If you have an active insider account, installing minecraft from the store would install a beta, as opposed to the release.

Also be aware that Mojang/Microsoft released Previews to replace the old beta system, so there is a chance that beta versions will no longer be available due to this.

**Comment by Rayth** [comment]
Marked as won't fix. Mojang have discontinued beta program.
