### ISSUE TITLE
Failed to find download links

### ISSUE THREAD

**Issue by AshUosis** [BedrockLauncher/BedrockLauncher#250]
Versions below 0.14.0.1 can't be downloaded

**Comment by Rayth** [comment]
Can you provide a full log and steps to reproduce this issue

**Comment by NT690** [comment]
```
2022-07-24 20:46:44.6808|DEBUG||Version: 2022.7.4.195
2022-07-24 20:46:44.7195|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2022-07-24 20:46:44.7195|DEBUG||Git Branch: lite
2022-07-24 20:46:44.7195|DEBUG||Git Commit: 3ed563d
2022-07-24 20:46:44.7195|DEBUG||Git Sha: 3ed563d2826badcfafa0817d0df8700c778f1e42
2022-07-24 20:46:44.7457|DEBUG||Application Starting...
2022-07-24 20:46:52.4930|DEBUG||Application Initalization Started!
2022-07-24 20:46:52.4930|DEBUG||Application Initalization Finished!
2022-07-24 20:47:00.1625|DEBUG||Preparing Application...
2022-07-24 20:47:11.0881|DEBUG||Checking for updates
2022-07-24 20:47:12.7624|DEBUG||Current tag: 2022.7.4.195
2022-07-24 20:47:12.7624|DEBUG||Latest tag: 2022.7.4.195
2022-07-24 20:47:12.7624|DEBUG||Preparing Application: DONE
2022-07-24 20:47:30.8671|DEBUG||Download start
2022-07-24 20:47:30.8671|DEBUG||Download starting
2022-07-24 20:47:31.5797|DEBUG||Download failed:
BedrockLauncher.Exceptions.PackageDownloadFailedException: Failed to Find Download Links
 ---> System.Exception: Failed to Find Download Links
 ---> System.Exception: first_node_or_throw
 ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at BedrockLauncher.UpdateProcessor.Extensions.NetworkExtensions.first_node_or_throw(XElement element, XName name) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Extensions\NetworkExtensions.cs:line 50
   --- End of inner exception stack trace ---
   at BedrockLauncher.UpdateProcessor.Extensions.NetworkExtensions.first_node_or_throw(XElement element, XName name) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Extensions\NetworkExtensions.cs:line 55
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.getDownloadLinks(String updateIdentity, Int32 revisionNumber, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 357
   --- End of inner exception stack trace ---
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.getDownloadLinks(String updateIdentity, Int32 revisionNumber, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 370
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.getDownloadLink(String updateIdentity, Int32 revisionNumber, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 376
   at BedrockLauncher.UpdateProcessor.Handlers.VersionManager.DownloadVersion(String versionName, String updateIdentity, Int32 revisionNumber, String destination, DownloadProgress progress, CancellationToken cancellationToken, VersionType type) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\VersionManager.cs:line 49
   at BedrockLauncher.Downloaders.VersionDownloader.DownloadVersion(String versionName, String uuid, Int32 revisionNumber, String destination, DownloadProgress progress, CancellationToken cancellationToken, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 43
   at BedrockLauncher.Handlers.PackageHandler.DownloadPackage(MCVersion v, String dlPath, CancellationTokenSource cancelSource) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 188
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.DownloadAndExtractPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 168
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 56
```
Is the log I got when I tried, and to reproduce it I:
1.  Created a new installation with a version below 0.14.0.1, in this case I used 0.13.0.0,
2. Attempted to play it.
and then the error popped up

**Comment by Rayth** [comment]
Can't be fixed. It literally only affects old old versions and has been an issue for a long time. Nothing we can do to control it.
