### ISSUE TITLE
unable to re-register the application

### ISSUE THREAD

**Issue by juliana2307** [BedrockLauncher/BedrockLauncher#258]
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.19.1003.0_x64__8wekyb3d8bbwe because this package is not compatible with the device. The package requires OS version 10.0.19041.0 or later on the Windows.Universal device family. The device is currently running OS version 10.0.18363.1256.
 ---> System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.19.1003.0_x64__8wekyb3d8bbwe because this package is not compatible with the device. The package requires OS version 10.0.19041.0 or later on the Windows.Universal device family. The device is currently running OS version 10.0.18363.1256.
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 462
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 218
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 229
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 59

**Comment by NT690** [comment]
it seems you need to update windows to install the new Minecraft version

**Comment by tresabhi** [comment]
Please update your Windows installation.

**Comment by juliana2307** [comment]
i will update thank you
