### ISSUE TITLE
App re-register failed

### ISSUE THREAD

**Issue by EmeraldThunder1** [BedrockLauncher/BedrockLauncher#276]
I've been trying to run the launcher on 1.16 and have come across this error which complains about a missing package. I have bought and installed the latest version of Minecraft Bedrock edition from the store.

```
App re-register failed:
System.Exception: Deployment failed: Another user has already installed a packaged version of this app. An unpackaged version cannot replace this. The conflicting package is Microsoft.MinecraftUWP and it was published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 596
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<ReRegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 562
```

**Comment by Rayth** [comment]
Try uninstall minecraft from control panel then use the launcher.

**Comment by Rayth** [comment]
closed due to no response
