### ISSUE TITLE
App re-register failed

### ISSUE THREAD

**Issue by SuperFluffyGame** [BedrockLauncher/BedrockLauncher#30]
That's the error I get.
This is the crash report.

I'm enrolled in the minecraft beta, and own minecraft win 10.
```
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
OK
OK
Current tag: 0.0.1.8
Latest tag: 0.0.1.8
New UWP version: 
251095452 c48e54d0-2d3d-4c26-85d3-60fade12f6e8 Microsoft.MinecraftUWP_1.17.201.70_x64__8wekyb3d8bbwe
New UWP version: 
251095453 db3b4f7e-6b5e-4cb3-9e56-38471135ba8a Microsoft.MinecraftUWP_1.17.201.0_x86__8wekyb3d8bbwe
New UWP version: 
251095450 9cffef9d-7866-4132-8bac-9419d74fb7d3 Microsoft.MinecraftUWP_1.17.201.70_x86__8wekyb3d8bbwe
New UWP version: 
251095448 4502050f-bafb-4887-b7ee-d0e52e3730f7 Microsoft.MinecraftUWP_1.17.201.0_arm__8wekyb3d8bbwe
New UWP version: 
251095451 a95ffda8-30cf-452b-a07e-ba7f0c1071cb Microsoft.MinecraftUWP_1.17.201.70_arm__8wekyb3d8bbwe
New UWP version: 
251083909 1062bba9-2045-4ea9-a67a-621edd2cd260 Microsoft.MinecraftUWP_1.17.2020.0_x64__8wekyb3d8bbwe
New UWP version: 
251083912 fcaf4d7c-91d5-4dc1-a423-b3c187310729 Microsoft.MinecraftUWP_1.17.2020.0_x86__8wekyb3d8bbwe
New UWP version: 
251083911 b45c54b2-f43b-4653-ae76-aee172876a55 Microsoft.MinecraftUWP_1.17.2020.70_x64__8wekyb3d8bbwe
New UWP version: 
251083910 4412505a-1249-4532-b710-7c5f99572643 Microsoft.MinecraftUWP_1.17.2020.70_x86__8wekyb3d8bbwe
Registering package
Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.17.2020.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.19011.0_x86__8wekyb3d8bbwe}
App re-register failed:
System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.17.2020.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.19011.0_x86__8wekyb3d8bbwe}
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.Methods.GameManager.<DeploymentProgressWrapper>d__42.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Methods\GameManager.cs:line 697
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.Methods.GameManager.<ReRegisterPackage>d__41.MoveNext() in D:\UserData\Source\mc_repos
```

**Comment by SuperFluffyGame** [comment]
its working now?
