### ISSUE TITLE
Application fails to parse XML at startup

### ISSUE THREAD

**Issue by MrDexstor** [BedrockLauncher/BedrockLauncher#310]
[Log_2022-10-28_19-35-25.log](https://github.com/BedrockLauncher/BedrockLauncher/files/9890300/Log_2022-10-28_19-35-25.log)
Help Me

## Translated Log
```
2022-10-28 19:35:25.9298|DEBUG||Version: 1.0.0.0
2022-10-28 19:35:26.0390|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2022-10-28 19:35:26.0390|DEBUG||Git Branch: lite
2022-10-28 19:35:26.0390|DEBUG||Git Commit: 3af40bf
2022-10-28 19:35:26.0390|DEBUG||Git Sha: 3af40bff61ca1767d8d0b6d751a0c13c827e8a83
2022-10-28 19:35:26.0390|DEBUG||Application Starting...
2022-10-28 19:35:26.5694|DEBUG||Application Initalization Started!
2022-10-28 19:35:26.5694|DEBUG||Application Initalization Finished!
2022-10-28 19:35:27.1466|DEBUG||System.Windows.Markup.XamlParseException: "A constructor call on type 'BedrockLauncher.MainWindow' that satisfies the specified binding constraints resulted in an exception being thrown.": line number '11' and the position in the string "9".
 ---> System.TypeInitializationException: The type initializer for 'BedrockLauncher.ViewModels.MainViewModel' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'BedrockLauncher.ViewModels.MainDataModel' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.BadImageFormatException: An attempt was made to load a program that has an invalid format. (0x8007000B)
   at WinRT.Platform.WindowsCreateStringReference(Char* sourceString, Int32 length, IntPtr* hstring_header, IntPtr* hstring)
   at WinRT.MarshalString.Pinnable.GetAbi()
   at WinRT.MarshalString.GetAbi(Pinnable&p)
   at WinRT.WinrtModule.GetActivationFactory(String runtimeClassId)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..ctor()
   at WinRT.ActivationFactory`1..cctor()
   --- End of inner exception stack trace ---
   at WinRT.ActivationFactory`1.ActivateInstance[I]()
   at Windows.Management.Deployment.PackageManager..ctor()
   at BedrockLauncher.Handlers.PackageHandler..ctor() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 40
   at BedrockLauncher.ViewModels.MainDataModel..ctor(ConstructorDepth __depth) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\ViewModels\MainDataModel.cs:line 32
   at BedrockLauncher.ViewModels.MainDataModel..ctor() in FAKE_POSTSHARP_DEBUGGER_DOCUMENT:line 16707565
   at BedrockLauncher.ViewModels.MainDataModel..cctor() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\ViewModels\MainDataModel.cs:line 19
   --- End of inner exception stack trace ---
   at BedrockLauncher.ViewModels.MainDataModel.SetBackwardsCommunicationHost(IBackwardsCommunication host) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\ViewModels\MainDataModel.cs:line 23
   at BedrockLauncher.ViewModels.MainViewModel..ctor(ConstructorDepth __depth) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\ViewModels\MainViewModel.cs:line 30
   at BedrockLauncher.ViewModels.MainViewModel..ctor() in FAKE_POSTSHARP_DEBUGGER_DOCUMENT:line 16707565
   at BedrockLauncher.ViewModels.MainViewModel..cctor() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\ViewModels\MainViewModel.cs:line 24
   --- End of inner exception stack trace ---
   at BedrockLauncher.ViewModels.MainViewModel.get_Default() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\ViewModels\MainViewModel.cs:line 24
   at BedrockLauncher.MainWindow..ctor() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\MainWindow.xaml.cs:line 44
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by tresabhi** [comment]
You are using an updated version. Please upgrade to the latest release.

**Comment by MrDexstor** [comment]
> You are using an updated version. Please upgrade to the latest release.

I am using the latest version downloaded from the website https://bedrocklauncher .github.io . I downloaded this version today, 4 hours ago.

**Comment by tresabhi** [comment]
The log reports version `1.0.0.0`. This is not the latest one. Have you read he installation instructions on the official website? The download does not include an installer.

**Comment by Rayth** [comment]
Tres the log says 1.0.0.0 on the latest version. I verified that myself
with another issue

**Comment by tresabhi** [comment]
Uh... Excuse my unaware nature. Re-opening...

**Comment by Rayth** [comment]
From translating the log to English, I suspect this may be a non English
character in the windows or installation name. Never seen it before with
this specific error though

**Comment by MrDexstor** [comment]
> Uh... Excuse my unaware nature. Re-opening...

Thank you so much for figuring out that the error is not in the version. I tried to deal with this error myself and it led to the foll
[Log_2022-10-28_21-36-47.log](https://github.com/BedrockLauncher/BedrockLauncher/files/9893041/Log_2022-10-28_21-36-47.log)
owing log file...
