### ISSUE TITLE
Launcher fails to find download links

### ISSUE THREAD

**Issue by AbbottMc** [BedrockLauncher/BedrockLauncher#311]
**Bedrock Launcher Version:** Latest Release.
**Issue:** Launch failed when choosen the Beta version Minecraft. But you can launch Preview version successfully. 
**Logs (For Minecraft Beta version):**
2022-11-01 15:18:08.7177|DEBUG||Version: 1.0.0.0
2022-11-01 15:18:08.7482|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2022-11-01 15:18:08.7482|DEBUG||Git Branch: lite
2022-11-01 15:18:08.7482|DEBUG||Git Commit: 3af40bf
2022-11-01 15:18:08.7482|DEBUG||Git Sha: 3af40bff61ca1767d8d0b6d751a0c13c827e8a83
2022-11-01 15:18:08.7504|DEBUG||Application Starting...
2022-11-01 15:18:08.8709|DEBUG||Application Initalization Started!
2022-11-01 15:18:08.8709|DEBUG||Application Initalization Finished!
2022-11-01 15:18:09.2816|DEBUG||Preparing Application...
2022-11-01 15:18:12.2576|DEBUG||Checking for updates
2022-11-01 15:18:13.8190|DEBUG||Current tag: 1.0.0.0
2022-11-01 15:18:13.8190|DEBUG||Latest tag: 2022.10.9.152
2022-11-01 15:18:13.8190|DEBUG||New version available!
2022-11-01 15:18:13.8190|DEBUG||Preparing Application: DONE
2022-11-01 15:18:46.3026|DEBUG||Refreshing Application...
2022-11-01 15:18:47.4254|DEBUG||Refreshing Application: DONE
2022-11-01 15:19:11.8142|DEBUG||Download start
2022-11-01 15:19:11.8333|DEBUG||Download starting
2022-11-01 15:19:13.0403|DEBUG||Download failed:
BedrockLauncher.Exceptions.PackageDownloadFailedException: Failed to Find Download Links
 ---> System.Exception: Failed to Find Download Links
 ---> System.Exception: first_node_or_throw
 ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at BedrockLauncher.UpdateProcessor.Extensions.NetworkExtensions.first_node_or_throw(XElement element, XName name) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Extensions\NetworkExtensions.cs:line 50
   --- End of inner exception stack trace ---
   at BedrockLauncher.UpdateProcessor.Extensions.NetworkExtensions.first_node_or_throw(XElement element, XName name) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Extensions\NetworkExtensions.cs:line 55
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.getDownloadLinks(String updateIdentity, Int32 revisionNumber, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 357
   --- End of inner exception stack trace ---
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.getDownloadLinks(String updateIdentity, Int32 revisionNumber, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 370
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.getDownloadLink(String updateIdentity, Int32 revisionNumber, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 376
   at BedrockLauncher.UpdateProcessor.Handlers.VersionManager.DownloadVersion(String versionName, String updateIdentity, Int32 revisionNumber, String destination, DownloadProgress progress, CancellationToken cancellationToken, VersionType type) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\VersionManager.cs:line 49
   at BedrockLauncher.Downloaders.VersionDownloader.DownloadVersion(String versionName, String packageID, Int32 revisionNumber, String destination, DownloadProgress progress, CancellationToken cancellationToken, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Downloaders\VersionDownloader.cs:line 44
   at BedrockLauncher.Handlers.PackageHandler.DownloadPackage(MCVersion v, String dlPath, CancellationTokenSource cancelSource) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 234
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.DownloadAndExtractPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 212
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 80
2022-11-01 15:19:13.4013|DEBUG||App launch finished!

**Comment by tresabhi** [comment]
Ah boy, this bug's back... Again.

**Comment by AbbottMc** [comment]
QwQ

**Comment by tresabhi** [comment]
🤨

**Comment by tresabhi** [comment]
💀

**Comment by TheEpikBoi** [comment]
Maybe we can link the version of the launcher in which the betas still work for the people who need it? Or are the links see just broken?

**Comment by Rayth** [comment]
The links are broken. I suspect they got removed from the store.

**Comment by TheEpikBoi** [comment]
This basically means the old betas are unusable now right?

**Comment by Rayth** [comment]
pretty much yeah. only android uses "beta" now everything else is preview

**Comment by TheEpikBoi** [comment]
Then maybe remove the betas from the list? What's the whose point of keeping them anyways if they don't work
