### ISSUE TITLE
 The type initializer for 'WinRT.ActivationFactory`1' threw an exception.

### ISSUE THREAD

**Issue by broskicoldi** [BedrockLauncher/BedrockLauncher#314]
```
BedrockLauncher.Exceptions.AppLaunchFailedException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..ctor()
   at WinRT.ActivationFactory`1..cctor()
   --- End of inner exception stack trace ---
   at WinRT.ActivationFactory`1.As(Guid iid)
   at Windows.System.AppDiagnosticInfo.Make___objRef_global__Windows_System_IAppDiagnosticInfoStatics2()
   at Windows.System.AppDiagnosticInfo.get__objRef_global__Windows_System_IAppDiagnosticInfoStatics2()
   at Windows.System.AppDiagnosticInfo.RequestInfoForPackageAsync(String packageFamilyName)
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 55
   --- End of inner exception stack trace ---
```

**Comment by tresabhi** [comment]
Are you using a 64 bit computer?

**Comment by Rayth** [comment]
can you share your log file (should be under Data/Logs in the directory you extracted the launcher from)

**Comment by Rayth** [comment]
The error code in your Log relates to a requisite of minecraft not being installed. Not sure what that could be.

Can you try install Minecraft from the microsoft store first, see if that works, and if it does, uninstall it again then try the launcher.

**Comment by Rayth** [comment]
That could also be it yes. Simply doing a windows update to a more recent version of Win10 would fix it
