### ISSUE TITLE
cant launch 1.19.31+

### ISSUE THREAD

**Issue by xsh4d0w** [BedrockLauncher/BedrockLauncher#317]
Hey, whenever I try to launch 1.19.40/1.19.41 it launches 1.19.30.
This is the log

```
2022-11-26 09:21:13.1538|DEBUG||Version: 1.0.0.0
2022-11-26 09:21:13.1984|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2022-11-26 09:21:13.1984|DEBUG||Git Branch: lite
2022-11-26 09:21:13.2009|DEBUG||Git Commit: 3af40bf
2022-11-26 09:21:13.2009|DEBUG||Git Sha: 3af40bff61ca1767d8d0b6d751a0c13c827e8a83
2022-11-26 09:21:13.2009|DEBUG||Application Starting...
2022-11-26 09:21:13.3943|DEBUG||Application Initalization Started!
2022-11-26 09:21:13.3943|DEBUG||Application Initalization Finished!
2022-11-26 09:21:14.7681|DEBUG||Preparing Application...
2022-11-26 09:21:17.4386|DEBUG||Checking for updates
2022-11-26 09:21:18.3748|DEBUG||Current tag: 1.0.0.0
2022-11-26 09:21:18.3748|DEBUG||Latest tag: 2022.10.9.152
2022-11-26 09:21:18.3748|DEBUG||New version available!
2022-11-26 09:21:18.3748|DEBUG||Preparing Application: DONE
2022-11-26 09:22:55.6028|DEBUG||Download start
2022-11-26 09:22:55.6028|DEBUG||Download starting
2022-11-26 09:22:56.4692|DEBUG||Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/8403b389-fb9e-48ca-aca7-13c91a733c3f?P1=1669451016&P2=404&P3=2&P4=jX8yJs2tH%2fipEKXFwM8ZNhP5WRAwkSxLFtESLaNEXbjeXoBdaBI26sS6nmrhcnF3cg8ajj20T91%2fL8gb7cY%2fHQ%3d%3d
2022-11-26 09:22:58.0175|DEBUG||Download failed:
BedrockLauncher.Exceptions.PackageDownloadFailedException: The requested address is not valid in its context. (tlu.dl.delivery.mp.microsoft.com:80)
 ---> System.Net.Http.HttpRequestException: The requested address is not valid in its context. (tlu.dl.delivery.mp.microsoft.com:80)
 ---> System.Net.Sockets.SocketException (10049): The requested address is not valid in its context.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at BedrockLauncher.UpdateProcessor.Handlers.VersionManager.DownloadVersion(String versionName, String updateIdentity, Int32 revisionNumber, String destination, DownloadProgress progress, CancellationToken cancellationToken, VersionType type) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\VersionManager.cs:line 54
   at BedrockLauncher.Downloaders.VersionDownloader.DownloadVersion(String versionName, String packageID, Int32 revisionNumber, String destination, DownloadProgress progress, CancellationToken cancellationToken, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Downloaders\VersionDownloader.cs:line 44
   at BedrockLauncher.Handlers.PackageHandler.DownloadPackage(MCVersion v, String dlPath, CancellationTokenSource cancelSource) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 234
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.DownloadAndExtractPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 212
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 80
2022-11-26 09:22:58.5772|DEBUG||App launch finished!
```

**Comment by tresabhi** [comment]
Are you on the latest version of windows? Try updating first.
