### ISSUE TITLE
Unable to load DLL 'BedrockLauncher.TokenBroker.dll'

### ISSUE THREAD

**Issue by illson2** [BedrockLauncher/BedrockLauncher#324]
```2022-12-11 11:47:07.0655|DEBUG||Version: 1.0.0.0
2022-12-11 11:47:07.1787|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2022-12-11 11:47:07.1787|DEBUG||Git Branch: lite
2022-12-11 11:47:07.1787|DEBUG||Git Commit: 3af40bf
2022-12-11 11:47:07.1787|DEBUG||Git Sha: 3af40bff61ca1767d8d0b6d751a0c13c827e8a83
2022-12-11 11:47:07.1787|DEBUG||Application Starting...
2022-12-11 11:47:07.7960|DEBUG||Application Initalization Started!
2022-12-11 11:47:07.7994|DEBUG||Application Initalization Finished!
2022-12-11 11:47:14.0354|DEBUG||Preparing Application...
2022-12-11 11:47:19.9782|DEBUG||Checking for updates
2022-12-11 11:47:20.4530|DEBUG||Current tag: 1.0.0.0
2022-12-11 11:47:20.4540|DEBUG||Latest tag: 2022.10.9.152
2022-12-11 11:47:20.4540|DEBUG||New version available!
2022-12-11 11:47:20.4540|DEBUG||Preparing Application: DONE
2022-12-11 11:47:38.5742|DEBUG||System.DllNotFoundException: Unable to load DLL 'BedrockLauncher.TokenBroker.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationTokenHelper.GetTotalWUAccounts()
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationManager.GetWUUsers() in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Authentication\AuthenticationManager.cs:line 28
   at BedrockLauncher.Controls.Setting_InsiderCombobox.ReloadList(Boolean save) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Controls\Setting_InsiderCombobox.xaml.cs:line 28
   at BedrockLauncher.Controls.Setting_InsiderCombobox.Grid_Loaded(Object sender, RoutedEventArgs e) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Controls\Setting_InsiderCombobox.xaml.cs:line 39
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)```

windows 11 pls help

**Comment by Rayth** [comment]
duplicate #313
