### ISSUE TITLE
package error

### ISSUE THREAD

**Issue by jean-raphael** [BedrockLauncher/BedrockLauncher#330]
Indiquez l’infrastructure « Microsoft.Services.Store.Engagement »

2022-12-21 20:18:53.2119|DEBUG||Registering package
2022-12-21 20:18:53.6396|DEBUG||Deployment failed: Windows ne peut pas installer le package Microsoft.MinecraftUWP_1.19.5101.0_x64__8wekyb3d8bbwe, car ce package dépend d’une infrastructure qui n’a pas pu être trouvée. Indiquez l’infrastructure « Microsoft.Services.Store.Engagement » publiée par « CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US », avec une architecture neutre ou de processeur x64 et la version minimale 10.0.1610.0, en plus de ce package à installer. Les infrastructures avec le nom « Microsoft.Services.Store.Engagement » installées actuellement sont : {Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe}
2022-12-21 20:18:53.6589|DEBUG||App registeration failed:
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Windows ne peut pas installer le package Microsoft.MinecraftUWP_1.19.5101.0_x64__8wekyb3d8bbwe, car ce package dépend d’une infrastructure qui n’a pas pu être trouvée. Indiquez l’infrastructure « Microsoft.Services.Store.Engagement » publiée par « CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US », avec une architecture neutre ou de processeur x64 et la version minimale 10.0.1610.0, en plus de ce package à installer. Les infrastructures avec le nom « Microsoft.Services.Store.Engagement » installées actuellement sont : {Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe}
 ---> System.Exception: Deployment failed: Windows ne peut pas installer le package Microsoft.MinecraftUWP_1.19.5101.0_x64__8wekyb3d8bbwe, car ce package dépend d’une infrastructure qui n’a pas pu être trouvée. Indiquez l’infrastructure « Microsoft.Services.Store.Engagement » publiée par « CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US », avec une architecture neutre ou de processeur x64 et la version minimale 10.0.1610.0, en plus de ce package à installer. Les infrastructures avec le nom « Microsoft.Services.Store.Engagement » installées actuellement sont : {Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe}
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 511
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 264
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 275
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 83
2022-12-21 20:18:53.6760|DEBUG||App launch finished!

**Comment by Rayth** [comment]
duplicate #327
