### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by keenanyafiqy** [BedrockLauncher/BedrockLauncher#339]
I was trying to launch Minecraft Bedrock Edition version 0.14+ but then when trying to launch the game, the game crashes and the error that shown up was

BedrockLauncher.Exceptions.PackageProcessHookFailedException: Object reference not set to an instance of an object.

Is this a bug from the launcher, or just me that doesn't installed enough program just to launch an old version of Minecraft?

**Comment by tresabhi** [comment]
I believe this has happened because Minecraft betas were discontinued. @Rayth, can you confirm?

**Comment by Rayth** [comment]
does theminecraft window pop up the crash?

**Comment by keenanyafiqy** [comment]
The window of the game opened with the name "Minecraft: Windows 10 Edition Beta" and then it crashes. Many of the research and found that Error "Object reference not set to an instance of an object." is because there is a code that the reference did not return to an object. I guess it's because the launcher code, or the package code

**Comment by Rayth** [comment]
can you upload a LOG file from the data/logs folder where you ran bedrocklauncher.exe, as well as your settings.json file

**Comment by keenanyafiqy** [comment]
Hmm.. hang on

**Comment by keenanyafiqy** [comment]
Where do I get the settings.json file?

**Comment by Rayth** [comment]
just upload it to here. you can attach files by dragging and dropping

**Comment by keenanyafiqy** [comment]
`BedrockLauncher.Exceptions.PackageProcessHookFailedException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at BedrockLauncher.Handlers.PackageHandler.<>c__DisplayClass27_0.<UpdatePackageHandle>b__0() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 458
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.<>c__DisplayClass27_0.<UpdatePackageHandle>b__0() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 474
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at BedrockLauncher.Handlers.PackageHandler.UpdatePackageHandle(AppActivationResult app) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 454
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 59`

**Comment by Rayth** [comment]
that's only the error. we need a full log file

**Comment by keenanyafiqy** [comment]
How do I get the log?

**Comment by keenanyafiqy** [comment]
I can't press the "View crash report" button since it was just crashing the entire launcher

**Comment by Rayth** [comment]
> can you upload a LOG file from the data/logs folder where you ran bedrocklauncher.exe, as well as your settings.json file

**Comment by keenanyafiqy** [comment]
> > can you upload a LOG file from the data/logs folder where you ran bedrocklauncher.exe, as well as your settings.json file

oh yeah

**Comment by keenanyafiqy** [comment]
> > can you upload a LOG file from the data/logs folder where you ran bedrocklauncher.exe, as well as your settings.json file

oh yeah

**Comment by keenanyafiqy** [comment]
[Log_2022-12-29_18-06-58.log](https://github.com/BedrockLauncher/BedrockLauncher/files/10352344/Log_2022-12-29_18-06-58.log)

**Comment by keenanyafiqy** [comment]
`
{
  "InstallationsSortMode": 0,
  "FetchVersionsFromMicrosoftStore": false,
  "AnimatePageTransitions": false,
  "CurrentTheme": "LatestUpdate",
  "KeepLauncherOpen": true,
  "UseBetaBuilds": false,
  "PortableMode": false,
  "FixedDirectory": "",
  "IsFirstLaunch": false,
  "CurrentInstallationUUID": "56419713-c492-4113-981b-c2d314110b26",
  "CurrentProfileUUID": "a7f1dccd-a53d-4d5c-99f5-5a062a330f12",
  "ShowReleases": true,
  "ShowBetas": true,
  "ShowPreviews": true,
  "CurrentInsiderAccountIndex": 1
}
`

**Comment by keenanyafiqy** [comment]
Oh wait so it depends on folder permission or what?

**Comment by Rayth** [comment]
your settings file doesn't have the location saved so forcing it to look somewhere else should fix that.

**Comment by keenanyafiqy** [comment]
Ohh so it's on the "FixedDirectory" field? So why do i HAVE TO COPY MY FREAKING 5 GB OF SAKE DATA

**Comment by keenanyafiqy** [comment]
IT DIDN"T WORK EITHER

**Comment by keenanyafiqy** [comment]
HECK NO I WASTED TIME COPYING ALL MY LAUNCHER DATA TO THE NEW FOLDER THIS IS A STORAGE WASTE
