### ISSUE TITLE
Package Registration Failed

### ISSUE THREAD

**Issue by Shurelia** [BedrockLauncher/BedrockLauncher#342]
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: 
 ---> System.Exception: Deployment failed: 
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 511
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 264
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 275
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 83
   
[Log_2023-01-06_13-24-00.log](https://github.com/BedrockLauncher/BedrockLauncher/files/10357842/Log_2023-01-06_13-24-00.log)

Already installed .Net 6.0.12

**Comment by Rayth** [comment]
Have you purchased minecraft?

**Comment by Shurelia** [comment]
> 

yes i do, but i dont know how to login onto my account in the launcher, i believe its something to do with my pc microsoft's account? cause im not logged into any accounts on my pc

**Comment by Rayth** [comment]
you need to be logged into a MS account on pc so that the launcher can access the store

**Comment by Shurelia** [comment]
> you need to be logged into a MS account on pc so that the launcher can access the store

ah i see, guess i cant use this too ig (using a modified win 10) well you can close this then thank you for the explanation!^^
