### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MasterPlay12** [BedrockLauncher/BedrockLauncher#344]
BedrockLauncher.Exceptions.AppLaunchFailedException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..ctor()
   at WinRT.ActivationFactory`1..cctor()
   --- End of inner exception stack trace ---
   at WinRT.ActivationFactory`1.As(Guid iid)
   at Windows.System.AppDiagnosticInfo.Make___objRef_global__Windows_System_IAppDiagnosticInfoStatics2()
   at Windows.System.AppDiagnosticInfo.get__objRef_global__Windows_System_IAppDiagnosticInfoStatics2()
   at Windows.System.AppDiagnosticInfo.RequestInfoForPackageAsync(String packageFamilyName)
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 55
   --- End of inner exception stack trace ---

**Comment by Rayth** [comment]
Please upload the latest log file for the launcher. You can find this, by going into the data/logs folder from where you launched BedrockLauncher.exe.
