### ISSUE TITLE
Problem with Microsoft.MinecraftUWP

### ISSUE THREAD

**Issue by grizone** [BedrockLauncher/BedrockLauncher#348]
latest log

2023-01-08 22:22:28.1789|DEBUG||Version: 1.0.0.0
2023-01-08 22:22:28.2028|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2023-01-08 22:22:28.2028|DEBUG||Git Branch: lite
2023-01-08 22:22:28.2028|DEBUG||Git Commit: 3af40bf
2023-01-08 22:22:28.2028|DEBUG||Git Sha: 3af40bff61ca1767d8d0b6d751a0c13c827e8a83
2023-01-08 22:22:28.2028|DEBUG||Application Starting...
2023-01-08 22:22:28.3581|DEBUG||Application Initalization Started!
2023-01-08 22:22:28.3581|DEBUG||Application Initalization Finished!
2023-01-08 22:22:29.1127|DEBUG||Preparing Application...
2023-01-08 22:22:31.9614|DEBUG||Checking for updates
2023-01-08 22:22:33.1656|DEBUG||Current tag: 1.0.0.0
2023-01-08 22:22:33.1656|DEBUG||Latest tag: 2022.10.9.152
2023-01-08 22:22:33.1656|DEBUG||New version available!
2023-01-08 22:22:33.1656|DEBUG||Preparing Application: DONE
2023-01-08 22:23:08.8714|DEBUG||Download start
2023-01-08 22:23:08.8714|DEBUG||Download starting
2023-01-08 22:23:09.1759|DEBUG||Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/f53d8369-e770-40c0-8408-1d7ac5aefe84?P1=1673225098&P2=404&P3=2&P4=JnvlyAxQKuFIOPWLKkmvwBMJqxzVme0jaumCs9M3TCIpLkbIHAZXOABFbSnxjd5RjASLX9Pi3vSW4pnA6aoZfQ%3d%3d
2023-01-08 22:27:04.6924|DEBUG||Download complete
2023-01-08 22:27:04.6924|DEBUG||Extraction started
2023-01-08 22:27:19.6436|DEBUG||Extracted successfully
2023-01-08 22:27:41.5185|DEBUG||Registering package
2023-01-08 22:27:41.6846|DEBUG||Deployment failed: Windows не удается установить пакет Microsoft.MinecraftUWP_1.19.5101.0_x64__8wekyb3d8bbwe, так как он не совместим с устройством. Пакет можно установить на устройствах семейства Windows.Universal с ОС версии 10.0.19041.0 или более поздней. Сейчас на устройстве используется ОС версии 10.0.17763.1577.
2023-01-08 22:27:41.7080|DEBUG||App registeration failed:
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Windows не удается установить пакет Microsoft.MinecraftUWP_1.19.5101.0_x64__8wekyb3d8bbwe, так как он не совместим с устройством. Пакет можно установить на устройствах семейства Windows.Universal с ОС версии 10.0.19041.0 или более поздней. Сейчас на устройстве используется ОС версии 10.0.17763.1577.
 ---> System.Exception: Deployment failed: Windows не удается установить пакет Microsoft.MinecraftUWP_1.19.5101.0_x64__8wekyb3d8bbwe, так как он не совместим с устройством. Пакет можно установить на устройствах семейства Windows.Universal с ОС версии 10.0.19041.0 или более поздней. Сейчас на устройстве используется ОС версии 10.0.17763.1577.
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 511
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 264
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 275
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 83
2023-01-08 22:27:41.7303|DEBUG||App launch finished!

**Comment by Rayth** [comment]
you need to update your version of windows.

**Comment by grizone** [comment]
ok
