### ISSUE TITLE
launcher closing after pressing "play"

### ISSUE THREAD

**Issue by GuyMapw** [BedrockLauncher/BedrockLauncher#355]
The trial version opens and runs well, but other versions it happens

Log
2023-01-21 13:10:41.2318|DEBUG||Version: 1.0.0.0
2023-01-21 13:10:41.3907|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2023-01-21 13:10:41.3907|DEBUG||Git Branch: lite
2023-01-21 13:10:41.3907|DEBUG||Git Commit: 3af40bf
2023-01-21 13:10:41.3907|DEBUG||Git Sha: 3af40bff61ca1767d8d0b6d751a0c13c827e8a83
2023-01-21 13:10:41.3907|DEBUG||Application Starting...
2023-01-21 13:10:42.3991|DEBUG||Application Initalization Started!
2023-01-21 13:10:42.4055|DEBUG||Application Initalization Finished!
2023-01-21 13:10:45.1025|DEBUG||Preparing Application...
2023-01-21 13:10:46.5041|DEBUG||System.DllNotFoundException: Unable to load DLL 'BedrockLauncher.TokenBroker.dll' or one of its dependencies: Não foi possível encontrar o módulo especificado. (0x8007007E)
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationTokenHelper.GetWUToken(Int32 userIndex, String& token)
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationManager.GetWUToken(Int32 relativeIndex) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Authentication\AuthenticationManager.cs:line 57
   at BedrockLauncher.UpdateProcessor.Handlers.VersionManager.<EnableUserAuthorization>b__20_0() in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\VersionManager.cs:line 237
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at BedrockLauncher.UpdateProcessor.Handlers.VersionManager.EnableUserAuthorization() in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\VersionManager.cs:line 237
2023-01-21 13:10:49.6806|DEBUG||Checking for updates
2023-01-21 13:10:50.8260|DEBUG||Current tag: 1.0.0.0
2023-01-21 13:10:50.8260|DEBUG||Latest tag: 2022.10.9.152
2023-01-21 13:10:50.8260|DEBUG||New version available!
2023-01-21 13:10:50.8260|DEBUG||Preparing Application: DONE
2023-01-21 13:11:13.5001|DEBUG||Download start
2023-01-21 13:11:13.5655|DEBUG||Error while Authenticating UserToken for Version Fetching:
System.DllNotFoundException: Unable to load DLL 'BedrockLauncher.TokenBroker.dll' or one of its dependencies: Não foi possível encontrar o módulo especificado. (0x8007007E)
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationTokenHelper.GetWUToken(Int32 userIndex, String& token)
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationManager.GetWUToken(Int32 relativeIndex) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Authentication\AuthenticationManager.cs:line 57
   at BedrockLauncher.Handlers.PackageHandler.<>c__DisplayClass26_0.<AuthenticateBetaUser>b__0() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 439
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at BedrockLauncher.Handlers.PackageHandler.AuthenticateBetaUser() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 439
2023-01-21 13:11:13.5793|DEBUG||Authentication failed:
BedrockLauncher.Exceptions.BetaAuthenticationFailedException: Unable to load DLL 'BedrockLauncher.TokenBroker.dll' or one of its dependencies: Não foi possível encontrar o módulo especificado. (0x8007007E)
 ---> System.DllNotFoundException: Unable to load DLL 'BedrockLauncher.TokenBroker.dll' or one of its dependencies: Não foi possível encontrar o módulo especificado. (0x8007007E)
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationTokenHelper.GetWUToken(Int32 userIndex, String& token)
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationManager.GetWUToken(Int32 relativeIndex) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Authentication\AuthenticationManager.cs:line 57
   at BedrockLauncher.Handlers.PackageHandler.<>c__DisplayClass26_0.<AuthenticateBetaUser>b__0() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 439
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at BedrockLauncher.Handlers.PackageHandler.AuthenticateBetaUser() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 439
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.DownloadAndExtractPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 212
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 80
2023-01-21 13:11:13.7967|DEBUG||App launch finished!

Help please

**Comment by Rayth** [comment]
if you're opening a trial version it means that you don't own minecraft so it wont work.

**Comment by GuyMapw** [comment]
is it necessary to buy the game to work?

**Comment by Rayth** [comment]
Either buy it, or have game pass. https://bedrocklauncher.github.io/faq/
