### ISSUE TITLE
Lanucher aren't installing ump minecraft runtime

### ISSUE THREAD

**Issue by hs233666** [BedrockLauncher/BedrockLauncher#356]
Lanucher won't automatically install runtime for minecraft ump , which causes launcher to crash on installing game.

**LOG**
2023-01-25 20:25:23.2804|DEBUG||Version: 1.0.0.0
2023-01-25 20:25:23.3015|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2023-01-25 20:25:23.3015|DEBUG||Git Branch: lite
2023-01-25 20:25:23.3015|DEBUG||Git Commit: 3af40bf
2023-01-25 20:25:23.3015|DEBUG||Git Sha: 3af40bff61ca1767d8d0b6d751a0c13c827e8a83
2023-01-25 20:25:23.3015|DEBUG||Application Starting...
2023-01-25 20:25:23.3975|DEBUG||Application Initalization Started!
2023-01-25 20:25:23.3975|DEBUG||Application Initalization Finished!
2023-01-25 20:25:23.8464|DEBUG||Preparing Application...
2023-01-25 20:25:31.7408|DEBUG||Checking for updates
2023-01-25 20:25:36.6379|DEBUG||Current tag: 1.0.0.0
2023-01-25 20:25:36.6379|DEBUG||Latest tag: 2022.10.9.152
2023-01-25 20:25:36.6379|DEBUG||New version available!
2023-01-25 20:25:36.6379|DEBUG||Preparing Application: DONE
2023-01-25 20:25:42.9957|DEBUG||Download start
2023-01-25 20:25:42.9957|DEBUG||Download starting
2023-01-25 20:25:44.3562|DEBUG||Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/f53d8369-e770-40c0-8408-1d7ac5aefe84?P1=1674665706&P2=404&P3=2&P4=a3lWcQ%2bzGR5ob1rqVOoGrGR8cdulZtDRtpfQ3wyRfE4E06ypUalYkvbSEjL0NJ3dxb9OyxfzrQWttlLsuYrPzQ%3d%3d
2023-01-25 20:36:19.6162|DEBUG||Registering package
2023-01-25 20:36:20.1437|DEBUG||Deployment failed: Windows 无法安装程序包 Microsoft.MinecraftUWP_1.19.5101.0_x64__8wekyb3d8bbwe，因为此程序包依赖于一个找不到的框架。请随要安装的此程序包一起提供由“CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US”发布的框架“Microsoft.Services.Store.Engagement”(具有中性或 x64 处理器体系结构，最低版本为 10.0.1610.0)。当前已安装的名称为“Microsoft.Services.Store.Engagement”的框架为: {Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe}
2023-01-25 20:36:20.1768|DEBUG||App registeration failed:
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Windows 无法安装程序包 Microsoft.MinecraftUWP_1.19.5101.0_x64__8wekyb3d8bbwe，因为此程序包依赖于一个找不到的框架。请随要安装的此程序包一起提供由“CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US”发布的框架“Microsoft.Services.Store.Engagement”(具有中性或 x64 处理器体系结构，最低版本为 10.0.1610.0)。当前已安装的名称为“Microsoft.Services.Store.Engagement”的框架为: {Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe}
 ---> System.Exception: Deployment failed: Windows 无法安装程序包 Microsoft.MinecraftUWP_1.19.5101.0_x64__8wekyb3d8bbwe，因为此程序包依赖于一个找不到的框架。请随要安装的此程序包一起提供由“CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US”发布的框架“Microsoft.Services.Store.Engagement”(具有中性或 x64 处理器体系结构，最低版本为 10.0.1610.0)。当前已安装的名称为“Microsoft.Services.Store.Engagement”的框架为: {Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe}
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 511
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 264
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 275
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 83
2023-01-25 20:36:20.1898|DEBUG||App launch finished!

**Comment by hs233666** [comment]
This problem may require a new-installed OS without XBOX to repeat.

**Comment by hs233666** [comment]
This issue may have reference with #335

**Comment by Rayth** [comment]
This issue means you need to either install .NET Desktop runtime, don't own mc, or try install mc from store first.

**Comment by hs233666** [comment]
> This issue means you need to either install .NET Desktop runtime, don't own mc, or try install mc from store first.

I have installed .net, its simply because minecraft lacks its runtime,and installing minecraft in storw definitely solves this problem.
I still suggest adding a tip for this situation, as the launcher would simply disappear after starting the game(though failed)

**Comment by Rayth** [comment]
> I have installed .net, its simply because minecraft lacks its runtime,and installing minecraft in store definitely solves this problem. I still suggest adding a tip for this situation, as the launcher would simply disappear after starting the game(though failed)

theres a launcher setting to keep it open when games launch
