### ISSUE TITLE
Error -2147018896 while backuping save data

### ISSUE THREAD

**Issue by Linecom-lik** [BedrockLauncher/BedrockLauncher#357]
# Error log
`System.IO.IOException: The specified file cannot be encrypted. : 'C:\Users\EBT01\AppData\Roaming\.minecraft_bedrock\installations\EBT01\RecoveryData\packageData\ud1320736602.dat'
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at BedrockLauncher.Handlers.BackupHandler.<>c__DisplayClass3_0.<<BackupData>b__0>d.MoveNext() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\BackupHandler.cs:line 83`
> This happens every time when I backing up my save data
So,I think this is a bug.
> And,I tested on my friend's computer,it's also happened.
# Environment
* Windows 10
* .NET 4.0.13

**Comment by Rayth** [comment]
try updating .NET but i had it happen with me too. I manually backup anyway and i always advise manual backups for safety
