### ISSUE TITLE
Uninstalls bedrock and crashes 

### ISSUE THREAD

**Issue by LeMustacheMan** [BedrockLauncher/BedrockLauncher#361]
Every time I try and play any installation on the launcher, it uninstalls Minecraft for Windows (bedrock) and closes the launcher. I've tried playing on different installations; latest release, 1.17.41, and latest beta. All of which crashed and uninstalled bedrock respectively. Any idea how to fix this or if it can be fixed?

**Comment by Rayth** [comment]
Well the way the launcher works. is it uninstalls the version you have so it can install the version you specify. If it's failing to install, please upload a log file from the `data/logs` folder found in the place you run bedrocklauncher.exe from

**Comment by LeMustacheMan** [comment]
> 
2023-02-16 19:48:58.4498|DEBUG||Version: 1.0.0.0
2023-02-16 19:48:58.4765|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2023-02-16 19:48:58.4765|DEBUG||Git Branch: lite
2023-02-16 19:48:58.4765|DEBUG||Git Commit: 3af40bf
2023-02-16 19:48:58.4765|DEBUG||Git Sha: 3af40bff61ca1767d8d0b6d751a0c13c827e8a83
2023-02-16 19:48:58.4765|DEBUG||Application Starting...
2023-02-16 19:48:58.6662|DEBUG||Application Initalization Started!
2023-02-16 19:48:58.6662|DEBUG||Application Initalization Finished!
2023-02-16 19:48:59.9014|DEBUG||Preparing Application...
2023-02-16 19:49:02.5495|DEBUG||Checking for updates
2023-02-16 19:49:03.8662|DEBUG||Current tag: 1.0.0.0
2023-02-16 19:49:03.8662|DEBUG||Latest tag: 2022.10.9.152
2023-02-16 19:49:03.8662|DEBUG||New version available!
2023-02-16 19:49:03.8662|DEBUG||Preparing Application: DONE
2023-02-16 19:49:10.7988|DEBUG||Removing package: Microsoft.MinecraftUWP_1.19.6201.0_x64__8wekyb3d8bbwe
2023-02-16 19:49:31.9381|DEBUG||Deployment done: Completed
2023-02-16 19:49:32.0328|DEBUG||Removal of package done: Microsoft.MinecraftUWP_1.19.6201.0_x64__8wekyb3d8bbwe
2023-02-16 19:49:32.1070|DEBUG||Registering package
2023-02-16 19:49:33.8023|DEBUG||Deployment failed: Deployment of package Microsoft.MinecraftUWP_1.17.4101.0_x64__8wekyb3d8bbwe with package origin Unsigned failed because no valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required.
2023-02-16 19:49:33.9775|DEBUG||App registeration failed:
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Deployment of package Microsoft.MinecraftUWP_1.17.4101.0_x64__8wekyb3d8bbwe with package origin Unsigned failed because no valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required.
 ---> System.Exception: Deployment failed: Deployment of package Microsoft.MinecraftUWP_1.17.4101.0_x64__8wekyb3d8bbwe with package origin Unsigned failed because no valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required.
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 511
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 264
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 275
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 83
2023-02-16 19:49:34.0149|DEBUG||App launch finished!

I own Minecraft through Game-pass, is that causing issues?

**Comment by LeMustacheMan** [comment]
> > 
> 
> 2023-02-16 19:48:58.4498|DEBUG||Version: 1.0.0.0 2023-02-16 19:48:58.4765|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher 2023-02-16 19:48:58.4765|DEBUG||Git Branch: lite 2023-02-16 19:48:58.4765|DEBUG||Git Commit: [3af40bf](https://github.com/BedrockLauncher/BedrockLauncher/commit/3af40bff61ca1767d8d0b6d751a0c13c827e8a83) 2023-02-16 19:48:58.4765|DEBUG||Git Sha: [3af40bf](https://github.com/BedrockLauncher/BedrockLauncher/commit/3af40bff61ca1767d8d0b6d751a0c13c827e8a83) 2023-02-16 19:48:58.4765|DEBUG||Application Starting... 2023-02-16 19:48:58.6662|DEBUG||Application Initalization Started! 2023-02-16 19:48:58.6662|DEBUG||Application Initalization Finished! 2023-02-16 19:48:59.9014|DEBUG||Preparing Application... 2023-02-16 19:49:02.5495|DEBUG||Checking for updates 2023-02-16 19:49:03.8662|DEBUG||Current tag: 1.0.0.0 2023-02-16 19:49:03.8662|DEBUG||Latest tag: 2022.10.9.152 2023-02-16 19:49:03.8662|DEBUG||New version available! 2023-02-16 19:49:03.8662|DEBUG||Preparing Application: DONE 2023-02-16 19:49:10.7988|DEBUG||Removing package: Microsoft.MinecraftUWP_1.19.6201.0_x64__8wekyb3d8bbwe 2023-02-16 19:49:31.9381|DEBUG||Deployment done: Completed 2023-02-16 19:49:32.0328|DEBUG||Removal of package done: Microsoft.MinecraftUWP_1.19.6201.0_x64__8wekyb3d8bbwe 2023-02-16 19:49:32.1070|DEBUG||Registering package 2023-02-16 19:49:33.8023|DEBUG||Deployment failed: Deployment of package Microsoft.MinecraftUWP_1.17.4101.0_x64__8wekyb3d8bbwe with package origin Unsigned failed because no valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required. 2023-02-16 19:49:33.9775|DEBUG||App registeration failed: BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Deployment of package Microsoft.MinecraftUWP_1.17.4101.0_x64__8wekyb3d8bbwe with package origin Unsigned failed because no valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required. ---> System.Exception: Deployment failed: Deployment of package Microsoft.MinecraftUWP_1.17.4101.0_x64__8wekyb3d8bbwe with package origin Unsigned failed because no valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required. at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 511 at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 264 --- End of inner exception stack trace --- at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 275 at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 83 2023-02-16 19:49:34.0149|DEBUG||App launch finished!
> 
> I own Minecraft through Game-pass, is that causing issues?

**Comment by Rayth** [comment]
gamepass should be fine. are you logged into the store and xbox app via the account which has gamepass?

**Comment by LeMustacheMan** [comment]
Yes, I have tried uninstalling the launcher and signing back into my Microsoft account but it still crashes.

**Comment by LeMustacheMan** [comment]
> gamepass should be fine. are you logged into the store and xbox app via the account which has gamepass?

I got it to work, it was because my pc was registered as part of my college, so dev mode was turned off, so it was interrupting the package launch.
