### ISSUE TITLE
Doesn't Work With WINE (Linux)

### ISSUE THREAD

**Issue by CommanderGL** [BedrockLauncher/BedrockLauncher#367]
I installed wine on a 64-bit Raspberry Pi 4 and when trying to run the launcher I get:

00d8:fixme:ver:GetFileVersionInfoExW flags 0x2 ignored
00d8:fixme:nls:CompareStringEx semi-stub behavior for flag(s) 0x8000000
Fatal error. Internal CLR error. (0x80131506)
   at NLog.Targets.FileTarget.PrepareForNewFile(System.String, NLog.LogEventInfo
)
   at NLog.Targets.FileTarget.InitializeFile(System.String, NLog.LogEventInfo)
   at NLog.Targets.FileTarget.ProcessLogEvent(NLog.LogEventInfo, System.String, 
System.ArraySegment`1<Byte>)
   at NLog.Targets.FileTarget.Write(NLog.LogEventInfo)
   at NLog.Targets.Target.Write(NLog.Common.AsyncLogEventInfo)
   at NLog.Targets.Target.WriteAsyncThreadSafe(NLog.Common.AsyncLogEventInfo)
   at NLog.Targets.Target.WriteAsyncLogEvent(NLog.Common.AsyncLogEventInfo)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(NLog.Targets.Target, NLog.Fil
ters.FilterResult, NLog.LogEventInfo, NLog.Common.AsyncContinuation)
   at NLog.LoggerImpl.Write(System.Type, NLog.Internal.TargetWithFilterChain, NL
og.LogEventInfo, NLog.LogFactory)
   at NLog.Logger.WriteToTargets(NLog.LogEventInfo, NLog.Internal.TargetWithFilt
erChain)
   at NLog.Logger.Log(NLog.LogEventInfo)
   at NLog.NLogTraceListener.ProcessLogEventInfo(NLog.LogLevel, System.String, S
ystem.String, System.Object[], System.Nullable`1<Int32>, System.Nullable`1<Syste
m.Diagnostics.TraceEventType>, System.Nullable`1<System.Guid>)
   at NLog.NLogTraceListener.WriteLine(System.String)
   at System.Diagnostics.TraceInternal.WriteLine(System.String)
   at System.Diagnostics.Trace.WriteLine(System.String)
   at BedrockLauncher.Handlers.RuntimeHandler.LogStartupInformation()
   at BedrockLauncher.Program.Main()
00d8:fixme:advapi:RegisterEventSourceW ((null),L".NET Runtime"): stub
00d8:fixme:advapi:ReportEventW (00000000CAFE4242,0x0001,0x0000,0x000003ff,0000000000000000,0x0001,0x00000000,000000000035AA30,0000000000000000): stub
00d8:err:eventlog:ReportEventW L"Application: BedrockLauncher.exe\nCoreCLR Version: 6.0.1423.7309\n.NET Version: 6.0.14\nDescription: The process was terminated due to an internal error in the .NET Runtime at IP 0000000000BC31AB (0000000000B10000) with exit code 80131506.\n"
00d8:fixme:advapi:DeregisterEventSource (00000000CAFE4242) stub
wine: Call from 000000007BC2BFA8 to unimplemented function KERNEL32.dll.RaiseFailFastException, aborting
wine: Call from 000000007B01129D to unimplemented function KERNEL32.dll.RaiseFailFastException, aborting

**Comment by Rayth** [comment]
we don't provide support for running on Non-Native windows platforms.
