### ISSUE TITLE
Launcher wont install

### ISSUE THREAD

**Issue by SamLeGgamer** [BedrockLauncher/BedrockLauncher#368]
Whenever im at the "choose folder"screen in the install prorgess and i click on "next" the installer just crashes

**Comment by Rayth** [comment]
can you download the latest release and tell us if it still happens

**Comment by SamLeGgamer** [comment]
Does not solve it


  *   Sam Le Goff

***@***.******@***.***>

Always availible

Van: Ryan ***@***.***>
Verzonden: maandag 13 maart 2023 04:45
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [BedrockLauncher/BedrockLauncher] Launcher wont install (Issue #368)


can you download the latest release and tell us if it still happens

**Comment by Rayth** [comment]
can you upload a log file from the data/logs folder where you ran the application from please

**Comment by Rayth** [comment]
We just pushed an update. Please try this one, then if it still fails, upload a log file:
https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2023.3.13.18

**Comment by SamLeGgamer** [comment]
Did not work


  *   Sam Le Goff

***@***.******@***.***>

Always availible

Van: Ryan ***@***.***>
Verzonden: maandag 13 maart 2023 23:05
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [BedrockLauncher/BedrockLauncher] Launcher wont install (Issue #368)


We just pushed an update. Please try this one, then if it still fails, upload a log file:
https://github.com/BedrockLauncher/BedrockLauncher/releases/tag/2023.3.13.18

**Comment by Rayth** [comment]
can you upload a LOG file as requested

**Comment by SamLeGgamer** [comment]
I did upload a file.
But if u want it in text:


2023-03-14 12:22:57.1166|DEBUG||Version: 2023.3.13.18
2023-03-14 12:22:57.2006|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2023-03-14 12:22:57.2006|DEBUG||Git Branch: lite
2023-03-14 12:22:57.2006|DEBUG||Git Commit: 239bf99
2023-03-14 12:22:57.2006|DEBUG||Git Sha: 239bf9909ea69018d1d234b4eb8a0e6c9983a9b0
2023-03-14 12:22:57.2075|DEBUG||Application Starting...
2023-03-14 12:22:57.6869|DEBUG||Application Initalization Started!
2023-03-14 12:22:57.6869|DEBUG||Application Initalization Finished!
2023-03-14 12:22:58.9785|DEBUG||Preparing Application...
2023-03-14 12:23:01.9200|DEBUG||Checking for updates
2023-03-14 12:23:02.9846|DEBUG||Current tag: 2023.3.13.18
2023-03-14 12:23:02.9846|DEBUG||Latest tag: 2023.3.13.18
2023-03-14 12:23:02.9883|DEBUG||Preparing Application: DONE
2023-03-14 12:23:08.8067|DEBUG||System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationTokenHelper.GetTotalWUAccounts()
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationManager.GetWUUsers() in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Authentication\AuthenticationManager.cs:line 28
   at BedrockLauncher.Pages.Settings.Accounts.Setting_InsiderCombobox.ReloadList(Boolean save) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Pages\Settings\Accounts\Setting_InsiderCombobox.xaml.cs:line 28
   at BedrockLauncher.Pages.Settings.Accounts.Setting_InsiderCombobox.Grid_Loaded(Object sender, RoutedEventArgs e) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Pages\Settings\Accounts\Setting_InsiderCombobox.xaml.cs:line 39
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)



Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows

Van: Ryan ***@***.***>
Verzonden: dinsdag 14 maart 2023 15:08
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [BedrockLauncher/BedrockLauncher] Launcher wont install (Issue #368)


can you upload a LOG file as requested

**Comment by Rayth** [comment]
1- Backup any existing data from minecraft if any
2- open the settings.json file in the "data" folder where you launched bedrocklauncher.exe from
3- change the following:
-  IsFirstLaunch from true to false
- CurrentInsiderAccountIndex from 0 to 1
4- start the launcher again.

**Comment by SamLeGgamer** [comment]
Well now its installed but whenever i try  to go to “accounts” in settings the lancher crashes and when i start any version i get exit code -2146233088 and this crash report:


BedrockLauncher.Exceptions.PackageProcessHookFailedException: Object reference not set to an instance of an object.
---> System.NullReferenceException: Object reference not set to an instance of an object.
   at BedrockLauncher.Handlers.PackageHandler.<>c__DisplayClass27_0.<UpdatePackageHandle>b__0() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 458
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.<>c__DisplayClass27_0.<UpdatePackageHandle>b__0() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 474
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at BedrockLauncher.Handlers.PackageHandler.UpdatePackageHandle(AppActivationResult app) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 454
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 59




  *   Sam Le Goff

***@***.******@***.***>

Always availible

Van: Ryan ***@***.***>
Verzonden: woensdag 15 maart 2023 13:53
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [BedrockLauncher/BedrockLauncher] Launcher wont install (Issue #368)


1- Backup any existing data from minecraft if any
2- open the settings.json file in the "data" folder where you launched bedrocklauncher.exe from
3- change the following:

  *   IsFirstLaunch from true to false
  *   CurrentInsiderAccountIndex from 0 to 1
4- start the launcher again.

**Comment by Rayth** [comment]
Can you upload a log from that crash
note- attaching logs in your email response doesn't upload them to github. I recommend actually opening github on your computer to upload it.

**Comment by SamLeGgamer** [comment]
What do you mean excactly?


  *   Sam Le Goff

***@***.******@***.***>

Always availible

Van: Ryan ***@***.***>
Verzonden: woensdag 15 maart 2023 17:48
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [BedrockLauncher/BedrockLauncher] Launcher wont install (Issue #368)


Can you upload a log from that crash
note- attaching logs in your email response doesn't upload them to github. I recommend actually opening github on your computer to upload it.

**Comment by Rayth** [comment]
Issue is resolved if you update your VC++ From microsoft: https://aka.ms/vs/17/release/vc_redist.x64.exe
