### ISSUE TITLE
Launcher crashes after pressing the ''next'' button on the ''Save/Load Launcher Data From'' Tab

### ISSUE THREAD

**Issue by RegularGithubUsername** [BedrockLauncher/BedrockLauncher#369]
Here's the log data:

2023-03-10 12:57:38.3615|DEBUG||Version: 1.0.0.0
2023-03-10 12:57:38.3855|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2023-03-10 12:57:38.3855|DEBUG||Git Branch: lite
2023-03-10 12:57:38.3855|DEBUG||Git Commit: 3af40bf
2023-03-10 12:57:38.3855|DEBUG||Git Sha: 3af40bff61ca1767d8d0b6d751a0c13c827e8a83
2023-03-10 12:57:38.3855|DEBUG||Application Starting...
2023-03-10 12:57:38.6454|DEBUG||Application Initalization Started!
2023-03-10 12:57:38.6465|DEBUG||Application Initalization Finished!
2023-03-10 12:57:39.9840|DEBUG||Preparing Application...
2023-03-10 12:57:42.4217|DEBUG||Checking for updates
2023-03-10 12:57:43.9559|DEBUG||Current tag: 1.0.0.0
2023-03-10 12:57:43.9559|DEBUG||Latest tag: 2022.10.9.152
2023-03-10 12:57:43.9559|DEBUG||New version available!
2023-03-10 12:57:43.9559|DEBUG||Preparing Application: DONE
2023-03-10 12:57:50.3427|DEBUG||System.DllNotFoundException: Unable to load DLL 'BedrockLauncher.TokenBroker.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationTokenHelper.GetTotalWUAccounts()
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationManager.GetWUUsers() in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Authentication\AuthenticationManager.cs:line 28
   at BedrockLauncher.Controls.Setting_InsiderCombobox.ReloadList(Boolean save) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Controls\Setting_InsiderCombobox.xaml.cs:line 28
   at BedrockLauncher.Controls.Setting_InsiderCombobox.Grid_Loaded(Object sender, RoutedEventArgs e) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Controls\Setting_InsiderCombobox.xaml.cs:line 39
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Rayth** [comment]
Can you download the latest release and tell us if it still happens.

**Comment by RegularGithubUsername** [comment]
Yeah It seems to be fixed now

**Comment by Lassebq** [comment]
Can this be reopened? Same BedrockLauncher.TokenBroker.dll seems to be missing in the currently latest release

**Comment by Rayth** [comment]
> Can this be reopened? Same BedrockLauncher.TokenBroker.dll seems to be missing in the currently latest release

No because it's not an issue with the launcher itself that we can find. It only happens to certain people and we're unsure why. I can assure you that the dll exists (runtimes>win-x64 folder) in the latest release download. I should know, I put the release together. 

Why this happens, we are unsure, and the only known fix we have at the moment, is some minor file modification on the user side. If you wish you can join our [Discord](https://discord.gg/Ar5SRBZcqn), open a support ticket and the support team can help with this. If you look in the folder I mentioned, and the DLL isn't there, please also join the discord and let us know with a screenshot of the folder.
