### ISSUE TITLE
Failed to Find Download Links

### ISSUE THREAD

**Issue by BOFOII** [BedrockLauncher/BedrockLauncher#377]
2023-04-03 06:17:32.2319|DEBUG||Version: 1.0.0.0
2023-04-03 06:17:32.4707|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2023-04-03 06:17:32.4707|DEBUG||Git Branch: 101d8e8
2023-04-03 06:17:32.4707|DEBUG||Git Commit: 101d8e8
2023-04-03 06:17:32.4707|DEBUG||Git Sha: 101d8e87beeeed84dc9f3b50c937f784d61993d9
2023-04-03 06:17:32.5464|DEBUG||Application Starting...
2023-04-03 06:17:38.5834|DEBUG||Application Initalization Started!
2023-04-03 06:17:38.5834|DEBUG||Application Initalization Finished!
2023-04-03 06:17:49.6412|DEBUG||Preparing Application...
2023-04-03 06:17:59.7360|DEBUG||Checking for updates
2023-04-03 06:18:01.6873|DEBUG||Current tag: 1.0.0.0
2023-04-03 06:18:01.6873|DEBUG||Latest tag: 2023.3.13.18
2023-04-03 06:18:01.6873|DEBUG||New version available!
2023-04-03 06:18:01.6873|DEBUG||Preparing Application: DONE
2023-04-03 06:18:09.4552|DEBUG||Refreshing Application...
2023-04-03 06:18:14.8461|DEBUG||Refreshing Application: DONE
2023-04-03 06:18:21.6969|DEBUG||Download start
2023-04-03 06:18:21.7083|DEBUG||Download starting
2023-04-03 06:18:23.1825|DEBUG||Download failed:
BedrockLauncher.Exceptions.PackageDownloadFailedException: Failed to Find Download Links
 ---> System.Exception: Failed to Find Download Links
 ---> System.Exception: first_node_or_throw
 ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at BedrockLauncher.UpdateProcessor.Extensions.NetworkExtensions.first_node_or_throw(XElement element, XName name) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Extensions\NetworkExtensions.cs:line 50
   --- End of inner exception stack trace ---
   at BedrockLauncher.UpdateProcessor.Extensions.NetworkExtensions.first_node_or_throw(XElement element, XName name) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Extensions\NetworkExtensions.cs:line 55
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.getDownloadLinks(String updateIdentity, Int32 revisionNumber, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 357
   --- End of inner exception stack trace ---
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.getDownloadLinks(String updateIdentity, Int32 revisionNumber, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 370
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.getDownloadLink(String updateIdentity, Int32 revisionNumber, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 376
   at BedrockLauncher.UpdateProcessor.Handlers.VersionManager.DownloadVersion(String versionName, String updateIdentity, Int32 revisionNumber, String destination, DownloadProgress progress, CancellationToken cancellationToken, VersionType type) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\VersionManager.cs:line 49
   at BedrockLauncher.Downloaders.VersionDownloader.DownloadVersion(String versionName, String packageID, Int32 revisionNumber, String destination, DownloadProgress progress, CancellationToken cancellationToken, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Downloaders\VersionDownloader.cs:line 44
   at BedrockLauncher.Handlers.PackageHandler.DownloadPackage(MCVersion v, String dlPath, CancellationTokenSource cancelSource) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 234
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.DownloadAndExtractPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 212
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 80
2023-04-03 06:18:23.7972|DEBUG||App launch finished!

**Comment by BOFOII** [comment]
I forgot what version it was in, maybe around 1.19.60+ but for other versions there is no problem

**Comment by Rayth** [comment]
You need to update your launcher to the latest release: https://github.com/BedrockLauncher/BedrockLauncher/releases/latest

Should solve your problem as we changed where the version files are downloaded from. You can copy the data folder from your old launcher location to the folder that bedrocklauncher.exe is in for the new one and it'll save all your settings etc
