### ISSUE TITLE
Application crashing when I have to choose the folder location

### ISSUE THREAD

**Issue by Erythefox** [BedrockLauncher/BedrockLauncher#382]
Operating system: Windows 10 64-bit
Processor: 11th gen intel core  i7-1165G7 @ 2.80GHz 1.69Ghz
Ram: 32GB
GPU:  NVIDIA GEFORCE  MX350

The issue happens when I have to choose between a fixed folder location or a portable/root folder and the moment that I press on "Next". Both of the option often result in the application crashing and then it sends a log in the log folder. Here is one of the log

2023-04-24 14:21:13.7345|DEBUG||Version: 2023.3.13.18
2023-04-24 14:21:13.7881|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2023-04-24 14:21:13.7881|DEBUG||Git Branch: lite
2023-04-24 14:21:13.7881|DEBUG||Git Commit: 239bf99
2023-04-24 14:21:13.7881|DEBUG||Git Sha: 239bf9909ea69018d1d234b4eb8a0e6c9983a9b0
2023-04-24 14:21:13.8085|DEBUG||Application Starting...
2023-04-24 14:21:14.4492|DEBUG||Application Initalization Started!
2023-04-24 14:21:14.4492|DEBUG||Application Initalization Finished!
2023-04-24 14:21:15.9983|DEBUG||Preparing Application...
2023-04-24 14:21:18.0561|DEBUG||Checking for updates
2023-04-24 14:21:19.6156|DEBUG||Current tag: 2023.3.13.18
2023-04-24 14:21:19.6156|DEBUG||Latest tag: 2023.3.13.18
2023-04-24 14:21:19.6156|DEBUG||Preparing Application: DONE
2023-04-24 14:21:22.6020|DEBUG||System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationTokenHelper.GetTotalWUAccounts()
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationManager.GetWUUsers() in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Authentication\AuthenticationManager.cs:line 28
   at BedrockLauncher.Pages.Settings.Accounts.Setting_InsiderCombobox.ReloadList(Boolean save) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Pages\Settings\Accounts\Setting_InsiderCombobox.xaml.cs:line 28
   at BedrockLauncher.Pages.Settings.Accounts.Setting_InsiderCombobox.Grid_Loaded(Object sender, RoutedEventArgs e) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Pages\Settings\Accounts\Setting_InsiderCombobox.xaml.cs:line 39
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

However, I rarely manage to get past the folder selection and after having to choose the profile name and directory it result into another crash when I click on "Next". I have been unable to figure out the steps to properly reproduce this step since the application often end up crashing during the selection of the folder location. Here is the log when it happens.

2023-04-24 14:18:49.6447|DEBUG||Version: 2023.3.13.18
2023-04-24 14:18:49.6832|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2023-04-24 14:18:49.6842|DEBUG||Git Branch: lite
2023-04-24 14:18:49.6842|DEBUG||Git Commit: 239bf99
2023-04-24 14:18:49.6842|DEBUG||Git Sha: 239bf9909ea69018d1d234b4eb8a0e6c9983a9b0
2023-04-24 14:18:49.6842|DEBUG||Application Starting...
2023-04-24 14:18:50.2535|DEBUG||Application Initalization Started!
2023-04-24 14:18:50.2535|DEBUG||Application Initalization Finished!
2023-04-24 14:18:51.3094|DEBUG||Preparing Application...
2023-04-24 14:18:51.4660|DEBUG||LoadTextDBVersions Failed! Generating Blank VersionTextDb
2023-04-24 14:18:51.4660|DEBUG||File: C:\Users\user\Documents\minecrat\Minecraft bedrock launcher\release\net6.0-windows10.0.17763.0\data\community_technical_versions.txt
2023-04-24 14:18:51.5724|DEBUG||System.IO.FileNotFoundException: Could not find file 'C:\Users\user\Documents\minecrat\Minecraft bedrock launcher\release\net6.0-windows10.0.17763.0\data\community_technical_versions.txt'.
File name: 'C:\Users\user\Documents\minecrat\Minecraft bedrock launcher\release\net6.0-windows10.0.17763.0\data\community_technical_versions.txt'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Databases.VersionTextDb.ReadFile(String filePath) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Databases\VersionTextDb.cs:line 57
   at BedrockLauncher.UpdateProcessor.Handlers.VersionManager.LoadTextDBVersions(String filePath) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\VersionManager.cs:line 207
2023-04-24 14:18:51.5781|DEBUG||LoadJsonDBVersions Failed! Generating Blank VersionJsonDb
2023-04-24 14:18:51.5781|DEBUG||File: C:\Users\user\Documents\minecrat\Minecraft bedrock launcher\release\net6.0-windows10.0.17763.0\data\community_versions.json
2023-04-24 14:18:51.5781|DEBUG||System.IO.FileNotFoundException: Could not find file 'C:\Users\user\Documents\minecrat\Minecraft bedrock launcher\release\net6.0-windows10.0.17763.0\data\community_versions.json'.
File name: 'C:\Users\user\Documents\minecrat\Minecraft bedrock launcher\release\net6.0-windows10.0.17763.0\data\community_versions.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Databases.VersionJsonDb.ReadJson(String filePath, Dictionary\`2 architectures) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Databases\VersionJsonDb.cs:line 34
   at BedrockLauncher.UpdateProcessor.Handlers.VersionManager.LoadJsonDBVersions(String filePath) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\VersionManager.cs:line 186
2023-04-24 14:18:52.8891|DEBUG||LoadTextDBVersions Failed! Generating Blank VersionTextDb
2023-04-24 14:18:52.8891|DEBUG||File: C:\Users\user\Documents\minecrat\Minecraft bedrock launcher\release\net6.0-windows10.0.17763.0\data\winstore_technical_versions.txt
2023-04-24 14:18:52.8891|DEBUG||System.IO.FileNotFoundException: Could not find file 'C:\Users\user\Documents\minecrat\Minecraft bedrock launcher\release\net6.0-windows10.0.17763.0\data\winstore_technical_versions.txt'.
File name: 'C:\Users\user\Documents\minecrat\Minecraft bedrock launcher\release\net6.0-windows10.0.17763.0\data\winstore_technical_versions.txt'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Databases.VersionTextDb.ReadFile(String filePath) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Databases\VersionTextDb.cs:line 57
   at BedrockLauncher.UpdateProcessor.Handlers.VersionManager.LoadTextDBVersions(String filePath) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\VersionManager.cs:line 207
2023-04-24 14:18:52.8891|DEBUG||LoadJsonDBVersions Failed! Generating Blank VersionJsonDb
2023-04-24 14:18:52.8891|DEBUG||File: C:\Users\user\Documents\minecrat\Minecraft bedrock launcher\release\net6.0-windows10.0.17763.0\data\winstore_versions.json
2023-04-24 14:18:52.8891|DEBUG||System.IO.FileNotFoundException: Could not find file 'C:\Users\user\Documents\minecrat\Minecraft bedrock launcher\release\net6.0-windows10.0.17763.0\data\winstore_versions.json'.
File name: 'C:\Users\user\Documents\minecrat\Minecraft bedrock launcher\release\net6.0-windows10.0.17763.0\data\winstore_versions.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Databases.VersionJsonDb.ReadJson(String filePath, Dictionary\`2 architectures) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Databases\VersionJsonDb.cs:line 34
   at BedrockLauncher.UpdateProcessor.Handlers.VersionManager.LoadJsonDBVersions(String filePath) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\VersionManager.cs:line 186
2023-04-24 14:18:53.1553|DEBUG||Checking for updates
2023-04-24 14:18:54.7170|DEBUG||Current tag: 2023.3.13.18
2023-04-24 14:18:54.7170|DEBUG||Latest tag: 2023.3.13.18
2023-04-24 14:18:54.7170|DEBUG||Preparing Application: DONE
2023-04-24 14:19:07.5854|DEBUG||System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationTokenHelper.GetTotalWUAccounts()
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationManager.GetWUUsers() in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Authentication\AuthenticationManager.cs:line 28
   at BedrockLauncher.Pages.Settings.Accounts.Setting_InsiderCombobox.ReloadList(Boolean save) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Pages\Settings\Accounts\Setting_InsiderCombobox.xaml.cs:line 28
   at BedrockLauncher.Pages.Settings.Accounts.Setting_InsiderCombobox.Grid_Loaded(Object sender, RoutedEventArgs e) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Pages\Settings\Accounts\Setting_InsiderCombobox.xaml.cs:line 39
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

I tried reinstalling .net Desktop Runtime multiple times and trying multiple version from 6.0.0 to 6.0.6 and the latest release (6.0.13) and the same issue happens. I took a look at the software and hardware requirement and my device seems to pass all of them. Since this is one of the first time I am opening an issue I might have forget to tell some details so if any more information is needed please let me know and I will try responding when I am available.

**Comment by Erythefox** [comment]
I installed VC++ runtime and rebooted my pc, however the issue is not fixed since the app still crash and gives the same log as before.
