### ISSUE TITLE
Support network paths for package files ('versions' directory)

### ISSUE THREAD

**Issue by Lucide** [BedrockLauncher/BedrockLauncher#389]
Hi,
I wonder if the packager can be made to work with remote `versions` (sub)folders shared via SMB. I'm not too familiar with the tools, the system packager might have some hardcoded security restrictions, but on the other hand, it might just be a matter of additional flags or path handling issues.

The use case here is simplifying build management by sharing a common (customized) game folder between machines to play with friends. Real machines in a LAN, or gpu-p -enabled VMs connected via high speed virtual switches.

Note that if I symlink a game subfolder (symlink to a network location), e.g. the `data` subfolder, the packager doesn't complain.\
Also note that, when it does fail, the modified game files are still loaded 🤔.

Log with a symlinked `version` *subfolder* (same with a sylinked `version`):

```
2023-05-14 18:54:58.3258|DEBUG||Version: 2023.4.30.195
2023-05-14 18:54:58.3494|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2023-05-14 18:54:58.3494|DEBUG||Git Branch: lite
2023-05-14 18:54:58.3494|DEBUG||Git Commit: e45d53f
2023-05-14 18:54:58.3494|DEBUG||Git Sha: e45d53f9fcb0a29c6a000d8ba1e5b6c84207a94c
2023-05-14 18:54:58.3494|DEBUG||Application Starting...
2023-05-14 18:54:58.5070|DEBUG||Application Initalization Started!
2023-05-14 18:54:58.5070|DEBUG||Application Initalization Finished!
2023-05-14 18:54:59.3452|DEBUG||Preparing Application...
2023-05-14 18:55:00.9653|DEBUG||Checking for updates
2023-05-14 18:55:01.4586|DEBUG||Current tag: 2023.4.30.195
2023-05-14 18:55:01.4586|DEBUG||Latest tag: 2023.4.30.195
2023-05-14 18:55:01.4586|DEBUG||Preparing Application: DONE
2023-05-14 18:55:11.0908|DEBUG||Skipping package removal - same path: Microsoft.MinecraftUWP_1.19.8101.0_x64__8wekyb3d8bbwe C:\Games\Minecraft\Data\versions\950a8a92-a558-48b7-872b-41dbd663f29a
2023-05-14 18:55:11.0908|DEBUG||Registering package
2023-05-14 18:55:11.1884|DEBUG||Deployment failed: error 0x80070005: Opening file from location: AppxManifest.xml failed with error: Access is denied.
.
2023-05-14 18:55:11.2198|DEBUG||App registeration failed:
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: error 0x80070005: Opening file from location: AppxManifest.xml failed with error: Access is denied.
.
 ---> System.Exception: Deployment failed: error 0x80070005: Opening file from location: AppxManifest.xml failed with error: Access is denied.
.
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 511
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 264
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 275
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 83
2023-05-14 18:55:12.0509|DEBUG||App launch finished!
```

**Comment by Rayth** [comment]
I don't see why it wouldn't work personally. From what I'm reading, the launcher is throwing an error, but it is actually loading as it should anyway? It says permission denied so its possible that there's a permission issue somewhere. I haven't personally tried this but I use SMB to access my media server on my raspberry pi from my windows pc

**Comment by Lucide** [comment]
It is saying that, but I don't think it's a genuine permission error. For the sake of experimenting, I gave the share full control (in "sharing settings" as well as NTFS ACLs), so the client has no restrictions whatsoever. It can even change the permissions themselves.

Yes, the game is loading as it should anyway. Of course, only if the package has already been installed.. I'm not sure how this project works, but I guess the appx is being built in such a way to reference the external game folder even "without re-registration" 😳?

Anyway, a symlinked subfolder works, but this approach has its drawbacks too.

**Comment by Rayth** [comment]
The launcher works by uninstalling and installing minecraft via the appx file, which is the same thing the store essentially does. It then symbolically links to the installation folder for whatever installation you use

**Comment by Lucide** [comment]
But it must be doing something with the package files at registration phase, because it attempts to access `AppxManifest.xml`. The launcher would have no reason to access file contents when creating folder symlinks.

I thought it was rebuilding the appx installer or something

**Comment by Rayth** [comment]
the launcher just downloads from the store itself and uses that file to install minecraft
