### ISSUE TITLE
Can't Play a Game

### ISSUE THREAD

**Issue by WhoIsDapn** [BedrockLauncher/BedrockLauncher#395]
System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.Management.Core.IApplicationDataManagerStaticsMethods.CreateForPackageFamily(IObjectReference _obj, String packageFamilyName)
   at Windows.Management.Core.ApplicationDataManager.CreateForPackageFamily(String packageFamilyName)
   at BedrockLauncher.Handlers.BackupHandler.<>c__DisplayClass3_0.<<BackupData>b__0>d.MoveNext() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\BackupHandler.cs:line 51

**Comment by WhoIsDapn** [comment]
2023-06-19 00:29:43.0872|DEBUG||Version: 2023.4.30.195
2023-06-19 00:29:43.1346|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2023-06-19 00:29:43.1346|DEBUG||Git Branch: lite
2023-06-19 00:29:43.1346|DEBUG||Git Commit: e45d53f
2023-06-19 00:29:43.1346|DEBUG||Git Sha: e45d53f9fcb0a29c6a000d8ba1e5b6c84207a94c
2023-06-19 00:29:43.1346|DEBUG||Application Starting...
2023-06-19 00:29:43.5084|DEBUG||Application Initalization Started!
2023-06-19 00:29:43.5084|DEBUG||Application Initalization Finished!
2023-06-19 00:29:46.3603|DEBUG||Preparing Application...
2023-06-19 00:29:50.4982|DEBUG||Checking for updates
2023-06-19 00:29:51.6250|DEBUG||Current tag: 2023.4.30.195
2023-06-19 00:29:51.6250|DEBUG||Latest tag: 2023.4.30.195
2023-06-19 00:29:51.6250|DEBUG||Preparing Application: DONE
2023-06-19 00:32:37.4906|DEBUG||Refreshing Application...
2023-06-19 00:32:40.4930|DEBUG||Refreshing Application: DONE
2023-06-19 00:32:47.0310|DEBUG||Registering package
2023-06-19 00:32:49.0934|DEBUG||Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.20.1.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.19011.0_x86__8wekyb3d8bbwe}
2023-06-19 00:32:49.2639|DEBUG||App registeration failed:
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.20.1.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.19011.0_x86__8wekyb3d8bbwe}
 ---> System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.20.1.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.19011.0_x86__8wekyb3d8bbwe}
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 511
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 264
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 275
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 83
2023-06-19 00:32:49.3354|DEBUG||App launch finished!

**Comment by Rayth** [comment]
Can you join our [Discord](https://discord.gg/Ar5SRBZcqn), open a support ticket in the support channel, and upload the log file there. State that you posted on github with Issue 395. We'll be able to help you better there
