### ISSUE TITLE
Not working on windows 11

### ISSUE THREAD

**Issue by legolloyd** [BedrockLauncher/BedrockLauncher#399]
When I create a new installation and then launch it, it immediately opens the latest Minecraft version.

**Comment by legolloyd** [comment]
also when go to the installations tab, and click on the install button for an installation, it gives me this error:

`BedrockLauncher.Exceptions.PackageDownloadFailedException: Failed to Find Download Links
 ---> System.Exception: Failed to Find Download Links
 ---> System.Exception: first_node_or_throw
 ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at BedrockLauncher.UpdateProcessor.Extensions.NetworkExtensions.first_node_or_throw(XElement element, XName name) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Extensions\NetworkExtensions.cs:line 50
   --- End of inner exception stack trace ---
   at BedrockLauncher.UpdateProcessor.Extensions.NetworkExtensions.first_node_or_throw(XElement element, XName name) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Extensions\NetworkExtensions.cs:line 55
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.getDownloadLinks(String updateIdentity, Int32 revisionNumber, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 357
   --- End of inner exception stack trace ---
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.getDownloadLinks(String updateIdentity, Int32 revisionNumber, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 370
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.getDownloadLink(String updateIdentity, Int32 revisionNumber, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 376
   at BedrockLauncher.UpdateProcessor.Handlers.VersionManager.DownloadVersion(String versionName, String updateIdentity, Int32 revisionNumber, String destination, DownloadProgress progress, CancellationToken cancellationToken, VersionType type) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\VersionManager.cs:line 49
   at BedrockLauncher.Downloaders.VersionDownloader.DownloadVersion(String versionName, String packageID, Int32 revisionNumber, String destination, DownloadProgress progress, CancellationToken cancellationToken, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 44
   at BedrockLauncher.Handlers.PackageHandler.DownloadPackage(MCVersion v, String dlPath, CancellationTokenSource cancelSource) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 234
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.DownloadAndExtractPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 212
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 80`

**Comment by Rayth** [comment]
What version are you trying to download?
