### ISSUE TITLE
Launcher Doesn't Open

### ISSUE THREAD

**Issue by fearocanity** [BedrockLauncher/BedrockLauncher#409]
I installed it properly in `C:/Program Files (x86)` directory, It doesn't open the launcher, and the log gave me this error...
Idk why it is referring to `D:` drive, I don't have external storage installed.
I also have the Dependencies installed properly...

log:
```
2023-07-19 13:01:47.6357|DEBUG||Version: 2023.4.30.195
2023-07-19 13:01:47.7036|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2023-07-19 13:01:47.7036|DEBUG||Git Branch: lite
2023-07-19 13:01:47.7036|DEBUG||Git Commit: e45d53f
2023-07-19 13:01:47.7036|DEBUG||Git Sha: e45d53f9fcb0a29c6a000d8ba1e5b6c84207a94c
2023-07-19 13:01:47.7036|DEBUG||Application Starting...
2023-07-19 13:01:48.3276|DEBUG||Application Initalization Started!
2023-07-19 13:01:48.3276|DEBUG||Application Initalization Finished!
2023-07-19 13:01:50.4168|DEBUG||Preparing Application...
2023-07-19 13:01:51.0386|DEBUG||System.NullReferenceException: Object reference not set to an instance of an object.
   at BedrockLauncher.Classes.BLProfileList.Load(String filePath, String lastProfile, String lastInstallation) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Classes\BLProfileList.cs:line 137
   at BedrockLauncher.ViewModels.MainDataModel.<LoadConfig>b__42_0() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\ViewModels\MainDataModel.cs:line 62
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at BedrockLauncher.ViewModels.MainDataModel.LoadConfig() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\ViewModels\MainDataModel.cs:line 60
   at BedrockLauncher.Program.<>c.<<OnApplicationLoaded>b__4_0>d.MoveNext() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Program.cs:line 54
--- End of stack trace from previous location ---
   at BedrockLauncher.ViewModels.MainViewModel.<>c__DisplayClass21_0.<<ShowWaitingDialog>b__0>d.MoveNext() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\ViewModels\MainViewModel.cs:line 93
--- End of stack trace from previous location ---
   at BedrockLauncher.ViewModels.MainViewModel.ShowWaitingDialog(Func`1 action) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\ViewModels\MainViewModel.cs:line 90
   at BedrockLauncher.Program.OnApplicationLoaded() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Program.cs:line 49
   at BedrockLauncher.MainWindow.Window_Initialized(Object sender, EventArgs e) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\MainWindow.xaml.cs:line 66
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Rayth** [comment]
All you did was place an application in the program files. It doesn't install. Can you try a different location such as documents or desktop.

The stack trace is just mentioning the location the file was compiled, and the person who compiled it does have a D drive

**Comment by fearocanity** [comment]
> All you did was place an application in the program files. It doesn't install. Can you try a different location such as documents or desktop.
> 
> The stack trace is just mentioning the location the file was compiled, and the person who compiled it does have a D drive

I already tried it, but no dice neither.

**Comment by fearocanity** [comment]
Strangely enough, deleting `.minecraft_bedrock` from `...\AppData\Roaming` fixes it...  now it works smoothly as expected.
