### ISSUE TITLE
Bedrock Launcher crashes, possible authentication issue

### ISSUE THREAD

**Issue by ocaduff** [BedrockLauncher/BedrockLauncher#414]
How I reproduce this error on my machine:
- Launch StartBedrockLauncher.exe
- Welcome Screen appears, click Next
- "One thing..." screen appears. Leave choice "Fixed Folder (Recommended)", click Next
- Application closes

In the BedrockLauncher/app/data/logs Folder, I can find a log file named "Log_2023-08-19_12-41-11.txt" with the following content:

```
2023-08-19 12:41:11.8514|DEBUG||Version: 2023.4.30.195
2023-08-19 12:41:11.8806|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2023-08-19 12:41:11.8806|DEBUG||Git Branch: lite
2023-08-19 12:41:11.8806|DEBUG||Git Commit: e45d53f
2023-08-19 12:41:11.8806|DEBUG||Git Sha: e45d53f9fcb0a29c6a000d8ba1e5b6c84207a94c
2023-08-19 12:41:11.8806|DEBUG||Application Starting...
2023-08-19 12:41:12.2290|DEBUG||Application Initalization Started!
2023-08-19 12:41:12.2290|DEBUG||Application Initalization Finished!
2023-08-19 12:41:15.0773|DEBUG||Preparing Application...
2023-08-19 12:41:16.6560|DEBUG||Checking for updates
2023-08-19 12:41:17.1352|DEBUG||Current tag: 2023.4.30.195
2023-08-19 12:41:17.1352|DEBUG||Latest tag: 2023.4.30.195
2023-08-19 12:41:17.1352|DEBUG||Preparing Application: DONE
2023-08-19 12:41:20.3219|DEBUG||System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationTokenHelper.GetTotalWUAccounts()
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationManager.GetWUUsers() in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Authentication\AuthenticationManager.cs:line 28
   at BedrockLauncher.Pages.Settings.Accounts.Setting_InsiderCombobox.ReloadList(Boolean save) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Pages\Settings\Accounts\Setting_InsiderCombobox.xaml.cs:line 28
   at BedrockLauncher.Pages.Settings.Accounts.Setting_InsiderCombobox.Grid_Loaded(Object sender, RoutedEventArgs e) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Pages\Settings\Accounts\Setting_InsiderCombobox.xaml.cs:line 39
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by ocaduff** [comment]
This comment lead me to the solution: https://github.com/BedrockLauncher/BedrockLauncher/issues/410#issuecomment-1649386391
On my machine, I was logged in with a different account than the admin.
