### ISSUE TITLE
On first run, asks to create profile then dies - log attached

### ISSUE THREAD

**Issue by dtw** [BedrockLauncher/BedrockLauncher#423]
2023-11-11 16:24:56.0588|DEBUG||Version: 2023.4.30.195
2023-11-11 16:24:56.0817|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2023-11-11 16:24:56.0817|DEBUG||Git Branch: lite
2023-11-11 16:24:56.0817|DEBUG||Git Commit: e45d53f
2023-11-11 16:24:56.0817|DEBUG||Git Sha: e45d53f9fcb0a29c6a000d8ba1e5b6c84207a94c
2023-11-11 16:24:56.0817|DEBUG||Application Starting...
2023-11-11 16:24:56.2312|DEBUG||Application Initalization Started!
2023-11-11 16:24:56.2312|DEBUG||Application Initalization Finished!
2023-11-11 16:24:56.9364|DEBUG||Preparing Application...
2023-11-11 16:24:58.3566|DEBUG||Checking for updates
2023-11-11 16:24:59.4324|DEBUG||Current tag: 2023.4.30.195
2023-11-11 16:24:59.4324|DEBUG||Latest tag: 2023.4.30.195
2023-11-11 16:24:59.4324|DEBUG||Preparing Application: DONE
2023-11-11 16:25:08.6421|DEBUG||System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationTokenHelper.GetTotalWUAccounts()
   at BedrockLauncher.UpdateProcessor.Authentication.AuthenticationManager.GetWUUsers() in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Authentication\AuthenticationManager.cs:line 28
   at BedrockLauncher.Pages.Settings.Accounts.Setting_InsiderCombobox.ReloadList(Boolean save) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Pages\Settings\Accounts\Setting_InsiderCombobox.xaml.cs:line 28
   at BedrockLauncher.Pages.Settings.Accounts.Setting_InsiderCombobox.Grid_Loaded(Object sender, RoutedEventArgs e) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Pages\Settings\Accounts\Setting_InsiderCombobox.xaml.cs:line 39
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Rayth** [comment]
1) Make sure your windows account is a microsoft account not a local windows account
2) Make sure you're running as admin. 

This error is most common ffrom number 1.
