### ISSUE TITLE
I cannot launch the game

### ISSUE THREAD

**Issue by KinglyMinecon** [BedrockLauncher/BedrockLauncher#426]
Error:
```
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Deployment of package Microsoft.MinecraftUWP_1.20.4102.0_x64__8wekyb3d8bbwe with package origin Unsigned failed because no valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required.
 ---> System.Exception: Deployment failed: Deployment of package Microsoft.MinecraftUWP_1.20.4102.0_x64__8wekyb3d8bbwe with package origin Unsigned failed because no valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required.
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 511
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 264
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 275
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 83
```

**Comment by Rayth** [comment]
Go into windows settings and enable developer mode.

**Comment by KinglyMinecon** [comment]
Thank you. This worked

**Comment by kaiden6633** [comment]
i need gelp to fix BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.21.4401.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install.
 ---> System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.21.4401.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install.
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 535
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 280
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 291
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 84 
notihng works

**Comment by kaiden6633** [comment]
also it uninstalls mc

**Comment by Rayth** [comment]
> i need gelp to fix BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.21.4401.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. ---> System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.21.4401.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 535 at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 280 --- End of inner exception stack trace --- at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 291 at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 84 notihng works

**Error when installing a version (usually an older one) and Log says missing Microsoft.Services.Store.Engagement**

Download and install this: https://github.com/RaythCo-Creations/downloads/raw/main/Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe.Appx

If this doesn't work, your store may be broken, but this can be tested by installing Minecraft from the store/official launcher, running it once then uninstalling it and using our launcher again.




> also it uninstalls mc

what did you expect it to do? you tried to install an older version so it needs to uninstall any newer one you have.

In future please create a new issue don't comment on old ones about completely different things.
