### ISSUE TITLE
Crashes on launching

### ISSUE THREAD

**Issue by LoboThExile** [BedrockLauncher/BedrockLauncher#431]
minecraft crashes on launching

![image](https://github.com/BedrockLauncher/BedrockLauncher/assets/66862740/cbcc01b4-7e79-414e-a3d8-8a94652fc8af)

video:
https://github.com/BedrockLauncher/BedrockLauncher/assets/66862740/feb77df3-06bf-4c22-a366-44aabcf9da00

BedrockLauncher.Exceptions.PackageProcessHookFailedException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at BedrockLauncher.Handlers.PackageHandler.<>c__DisplayClass27_0.<UpdatePackageHandle>b__0() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 458
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.<>c__DisplayClass27_0.<UpdatePackageHandle>b__0() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 474
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at BedrockLauncher.Handlers.PackageHandler.UpdatePackageHandle(AppActivationResult app) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 454
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 59

**Comment by IhorLihavn** [comment]
i have the same error message, does solution exist?
