### ISSUE TITLE
error help please

### ISSUE THREAD

**Issue by T0temichschneller** [BedrockLauncher/BedrockLauncher#435]
BedrockLauncher.Exceptions.AppLaunchFailedException: The type initializer for 'WinRT.Projections' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'WinRT.Projections' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Numerics.Vectors, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Не удается найти указанный файл.
File name: 'System.Numerics.Vectors, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at WinRT.Projections..cctor()
   --- End of inner exception stack trace ---
   at WinRT.Projections.FindCustomHelperTypeMapping(Type publicType, Boolean filterToRuntimeClass)
   at WinRT.ComWrappersSupport.CreateTypedRcwFactory(Type implementationType, String runtimeClassName)
   at WinRT.ComWrappersSupport.<>c.<GetTypedRcwFactory>b__65_0(Type classType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at WinRT.ComWrappersSupport.GetTypedRcwFactory(Type implementationType)
   at WinRT.DefaultComWrappers.CreateObject(IntPtr externalComObject)
   at WinRT.DefaultComWrappers.CreateObject(IntPtr externalComObject, CreateObjectFlags flags)
   at System.Runtime.InteropServices.ComWrappers.CallCreateObject(ComWrappersScenario scenario, ComWrappers comWrappersImpl, IntPtr externalComObject, CreateObjectFlags flags)
   at System.Runtime.InteropServices.ComWrappers.TryGetOrCreateObjectForComInstanceInternal(ObjectHandleOnStack comWrappersImpl, Int64 wrapperId, IntPtr externalComObject, IntPtr innerMaybe, CreateObjectFlags flags, ObjectHandleOnStack wrapper, ObjectHandleOnStack retValue)
   at System.Runtime.InteropServices.ComWrappers.TryGetOrCreateObjectForComInstanceInternal(ComWrappers impl, IntPtr externalComObject, IntPtr innerMaybe, CreateObjectFlags flags, Object wrapperMaybe, Object& retValue)
   at System.Runtime.InteropServices.ComWrappers.GetOrCreateObjectForComInstance(IntPtr externalComObject, CreateObjectFlags flags)
   at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr, Boolean tryUseCache)
   at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr)
   at WinRT.MarshalInspectable`1.FromAbi(IntPtr ptr)
   at WinRT.MarshalInterface`1.FromAbi(IntPtr ptr)
   at ABI.Windows.System.IAppDiagnosticInfoStatics2Methods.RequestInfoForPackageAsync(IObjectReference _obj, String packageFamilyName)
   at Windows.System.AppDiagnosticInfo.RequestInfoForPackageAsync(String packageFamilyName)
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 55
   --- End of inner exception stack trace ---

**Comment by T0temichschneller** [comment]
[Log_2024-01-26_18-54-50.log](https://github.com/BedrockLauncher/BedrockLauncher/files/14066294/Log_2024-01-26_18-54-50.log)

**Comment by T0temichschneller** [comment]
I downloaded .net 6.0 and now it crashes at 51% when registering packages

**Comment by Rayth** [comment]
> I downloaded .net 6.0 and now it crashes at 51% when registering packages

can you upload a new log with this error

**Comment by T0temichschneller** [comment]
[Log_2023-12-28_18-48-56.log](https://github.com/BedrockLauncher/BedrockLauncher/files/14066330/Log_2023-12-28_18-48-56.log)

**Comment by T0temichschneller** [comment]
Uploading 2024-01-26 19-00-18.mp4…

**Comment by T0temichschneller** [comment]
Check video

https://github.com/BedrockLauncher/BedrockLauncher/assets/129697665/5d147261-3790-4b00-b2c1-9ab1b180156f

**Comment by Rayth** [comment]
does your microsoft store work normally?

**Comment by T0temichschneller** [comment]
yes

**Comment by Rayth** [comment]
can you try installing minecraft via the official launcher then run it once, uninstall it via settings>apps and try this launcher.

If it's already installed, you will need to uninstall it first.

Please note if you don't own minecraft or have a gamepass subscription this launcher will not work either

**Comment by T0temichschneller** [comment]
oh stop.... no, no working

**Comment by T0temichschneller** [comment]
i cant start microsoft store

**Comment by Rayth** [comment]
That'll be why it's not working then. Contact microsoft about a broken store then it should work

**Comment by T0temichschneller** [comment]
i just reinstall microsoft store. minecraft working😀
