### ISSUE TITLE
Launcher crashing on startup

### ISSUE THREAD

**Issue by ScapeWimbledon** [BedrockLauncher/BedrockLauncher#445]
After starting launcher, it freezes for a second and crashes, system is fresh and i have installed Minecraft Bedrock already
here is the log:

2024-04-02 17:14:23.1689|DEBUG||Version: 2023.4.30.195
2024-04-02 17:14:23.2059|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2024-04-02 17:14:23.2059|DEBUG||Git Branch: lite
2024-04-02 17:14:23.2059|DEBUG||Git Commit: e45d53f
2024-04-02 17:14:23.2059|DEBUG||Git Sha: e45d53f9fcb0a29c6a000d8ba1e5b6c84207a94c
2024-04-02 17:14:23.2059|DEBUG||Application Starting...
2024-04-02 17:14:23.4422|DEBUG||Application Initalization Started!
2024-04-02 17:14:23.4422|DEBUG||Application Initalization Finished!
2024-04-02 17:14:24.4624|DEBUG||Preparing Application...
2024-04-02 17:14:26.2720|DEBUG||System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at BedrockLauncher.Downloaders.VersionDownloader.UpdateVersionList(ObservableCollection`1 versions, Boolean OnLoad) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 77
   at BedrockLauncher.ViewModels.MainDataModel.<>c__DisplayClass41_0.<<LoadVersions>b__0>d.MoveNext() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\ViewModels\MainDataModel.cs:line 52
--- End of stack trace from previous location ---
   at BedrockLauncher.ViewModels.MainDataModel.LoadVersions(Boolean onLoad) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\ViewModels\MainDataModel.cs:line 47
   at BedrockLauncher.Program.<>c.<<OnApplicationLoaded>b__4_0>d.MoveNext() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Program.cs:line 55
--- End of stack trace from previous location ---
   at BedrockLauncher.ViewModels.MainViewModel.<>c__DisplayClass21_0.<<ShowWaitingDialog>b__0>d.MoveNext() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\ViewModels\MainViewModel.cs:line 93
--- End of stack trace from previous location ---
   at BedrockLauncher.ViewModels.MainViewModel.ShowWaitingDialog(Func`1 action) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\ViewModels\MainViewModel.cs:line 90
   at BedrockLauncher.Program.OnApplicationLoaded() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Program.cs:line 49
   at BedrockLauncher.MainWindow.Window_Initialized(Object sender, EventArgs e) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\MainWindow.xaml.cs:line 66
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Rayth** [comment]
can you try again i think this was due to something we were trying to do earlier i might've just fixed it.

**Comment by ScapeWimbledon** [comment]
it still crashes, i tried changing "IsFirstLaunch" to false and "CurrentInsiderAccountIndex" to 1 in settings.json but it doesn`t help

**Comment by ScapeWimbledon** [comment]
how to reopen

**Comment by ScapeWimbledon** [comment]
sorry i missclicked

**Comment by Rayth** [comment]
> it still crashes, i tried changing "IsFirstLaunch" to false and "CurrentInsiderAccountIndex" to 1 in settings.json but it doesn`t help

can you go to `%appdata%\.minecraft_bedrock` folder and delete `community_technical_versions.txt` and `community_versions.json`

this will force it to redownload from the server. If it still fails, delet them again, wait 5-10mins and try again

**Comment by ScapeWimbledon** [comment]
No, it still crashes, i tried wait a little while but it doesn`t help

**Comment by ScapeWimbledon** [comment]
i fixed it myself by deleting .minecraft_bedrock folder and launching launcher. anyways, thanks for help
