### ISSUE TITLE
[Issue] The game fails to start

### ISSUE THREAD

**Issue by wtlgo** [BedrockLauncher/BedrockLauncher#450]
Hello! When I press "Play" the Minecraft window appears for one moment and disappears completely.
Here are the logs:

```log
2024-04-17 02:26:20.5359|DEBUG||Version: 2023.4.30.195
2024-04-17 02:26:20.6356|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2024-04-17 02:26:20.6356|DEBUG||Git Branch: lite
2024-04-17 02:26:20.6356|DEBUG||Git Commit: e45d53f
2024-04-17 02:26:20.6356|DEBUG||Git Sha: e45d53f9fcb0a29c6a000d8ba1e5b6c84207a94c
2024-04-17 02:26:20.6651|DEBUG||Application Starting...
2024-04-17 02:26:22.4426|DEBUG||Application Initalization Started!
2024-04-17 02:26:22.4426|DEBUG||Application Initalization Finished!
2024-04-17 02:26:27.1408|DEBUG||Preparing Application...
2024-04-17 02:26:31.5619|DEBUG||Checking for updates
2024-04-17 02:26:32.8829|DEBUG||Current tag: 2023.4.30.195
2024-04-17 02:26:32.8829|DEBUG||Latest tag: 2023.4.30.195
2024-04-17 02:26:32.8829|DEBUG||Preparing Application: DONE
2024-04-17 02:26:37.0808|DEBUG||App deregisteration failed:
BedrockLauncher.Exceptions.PackageDeregistrationFailedException: The system cannot find the drive specified. (0x8007000F)
 ---> System.Runtime.InteropServices.COMException (0x8007000F): The system cannot find the drive specified. (0x8007000F)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at BedrockLauncher.Handlers.PackageHandler.UnregisterPackage(MCVersion v, Boolean keepVersion, Boolean mustMatchVersion) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 335
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.UnregisterPackage(MCVersion v, Boolean keepVersion, Boolean mustMatchVersion) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 362
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 82
2024-04-17 02:26:37.4510|DEBUG||App launch finished!
```

The client is located at `G:\Minecraft\Clients\BedrockLauncher` and has portable mode enabled

**Comment by Rayth** [comment]
try disabling portable mode. the whole thing is technically portable now. if the mc window appears that doesn't sound like a launcher issue though

**Comment by Rayth** [comment]
Closing due to inactivity
