### ISSUE TITLE
Problem when finished downloading version

### ISSUE THREAD

**Issue by himansure** [BedrockLauncher/BedrockLauncher#469]
I downloading the 1.20.12 version but they install in 98%(minecraft:uwp) they disappear
Here the logs:
2024-06-21 22:41:56.2555|DEBUG||Version: 2024.5.31.2
2024-06-21 22:41:56.3108|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2024-06-21 22:41:56.3108|DEBUG||Git Branch: lite
2024-06-21 22:41:56.3108|DEBUG||Git Commit: 660a061
2024-06-21 22:41:56.3108|DEBUG||Git Sha: 660a0612a88faec1823e719a9ef7d5d02f888e3f
2024-06-21 22:41:56.3142|DEBUG||Application Starting...
2024-06-21 22:41:56.6259|DEBUG||Application Initalization Started!
2024-06-21 22:41:56.6259|DEBUG||Application Initalization Finished!
2024-06-21 22:41:58.1105|DEBUG||Preparing Application...
2024-06-21 22:42:05.4524|DEBUG||Checking for updates
2024-06-21 22:42:08.5183|DEBUG||Current tag: 2024.5.31.2
2024-06-21 22:42:08.5183|DEBUG||Latest tag: 2024.5.31.2
2024-06-21 22:42:08.5183|DEBUG||Preparing Application: DONE
2024-06-21 22:42:50.5134|DEBUG||Skipping package removal - same path: Microsoft.MinecraftUWP_1.20.1201.0_x64__8wekyb3d8bbwe D:\mcbr\versions\8cd36a7b-2da0-4389-ad6e-06f975a336ca
2024-06-21 22:42:50.5233|DEBUG||Registering package
2024-06-21 22:42:52.6326|DEBUG||Deployment failed: Another user has already installed an unpackaged version of this app. The current user cannot replace this with a packaged version. The conflicting package is Microsoft.MinecraftUWP and it was published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US.
2024-06-21 22:42:52.8065|DEBUG||App registeration failed:
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Another user has already installed an unpackaged version of this app. The current user cannot replace this with a packaged version. The conflicting package is Microsoft.MinecraftUWP and it was published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US.
 ---> System.Exception: Deployment failed: Another user has already installed an unpackaged version of this app. The current user cannot replace this with a packaged version. The conflicting package is Microsoft.MinecraftUWP and it was published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US.
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 511
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 264
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 275
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 83
2024-06-21 22:42:52.8699|DEBUG||App launch finished!
![image](https://github.com/BedrockLauncher/BedrockLauncher/assets/149285397/8e2b4c0f-f7ca-4877-aabc-903a3631b0c3)

Sorry for my poor language.

**Comment by Rayth** [comment]
You need to uninstall the minecraft you had installed prior to using the
launcher. Make sure your saves are backed up

**Comment by himansure** [comment]
you mean I unistall MC Win10 in microsoft?

**Comment by Rayth** [comment]
Yes uninstall the game as you have it already. The launcher cannot
overwrite the pre existing installation

**Comment by himansure** [comment]
How to completely delete Bedrock launcher Files?
