### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by lol216** [BedrockLauncher/BedrockLauncher#47]
Application Starting...
Application Pre-Initalization Finished!
Checking for updates
Current tag: 0.0.2.1
Latest tag: 0.0.2.1
Registering package
Deployment progress: Processing 0%
Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.17.1004.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe}
App re-register failed:
System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.17.1004.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe}
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 596
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<ReRegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 562
Version list update check failed:
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Connection.SyncRead(HttpWebRequest request, Boolean userRetrievedStream, Boolean probeRead)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<doHttpRequest>d__26.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 329
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<fetchConfigLastChanged>d__29.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 361
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.Downloaders.VersionDownloader.<LoadFromAPI>d__17.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 192
Version list update check failed:
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.TlsStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Connection.SyncRead(HttpWebRequest request, Boolean userRetrievedStream, Boolean probeRead)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<doHttpRequest>d__26.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 329
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<fetchConfigLastChanged>d__29.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 361
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.Downloaders.VersionDownloader.<LoadFromAPI_Technical>d__16.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 171
CantFindJavaLauncher: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Minecraft Launcher\Minecraft Launcher.lnk
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at BedrockLauncher.MainWindow.<NavigateToJavaLauncher>b__21_1() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\MainWindow.xaml.cs:line 223
Registering package
Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.17.1004.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe}
App re-register failed:
System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.17.1004.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.18101.0_x86__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.18101.0_x64__8wekyb3d8bbwe}
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 596
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<ReRegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 562

**Comment by CoolAbhi1290** [comment]
Please provide a more detailed error. I'm marking this as invalid for the time being.

**Comment by Rayth** [comment]
You can't get a more detailed error. What we do need though is information about the users computer. Operating system, 32bit or 64bit etc. However it looks like a store issue.

**Comment by CoolAbhi1290** [comment]
I meant I need more information on what happened. You can't just dump the log and expect us to understand what went wrong.

**Comment by CoolAbhi1290** [comment]
I'm closing this issue as no explanation was provided

**Comment by TresAbhi** [comment]
Closing the due to inactivity
