### ISSUE TITLE
e

### ISSUE THREAD

**Issue by Pepsyah** [BedrockLauncher/BedrockLauncher#472]
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Das Paket Microsoft.MinecraftWindowsBeta_1.21.1024.0_x64__8wekyb3d8bbwe kann von Windows nicht installiert werden, da es von einem Framework abhängig ist, das nicht gefunden wurde. Stellen Sie das von CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US veröffentlichte Framework Microsoft.Services.Store.Engagement mit einer neutralen oder x64-Prozessorarchitektur und Mindestversion 10.0.1610.0 zusammen mit dem zu installierenden Paket bereit. Die derzeit installierten Frameworks mit dem Namen Microsoft.Services.Store.Engagement sind: {}
 ---> System.Exception: Deployment failed: Das Paket Microsoft.MinecraftWindowsBeta_1.21.1024.0_x64__8wekyb3d8bbwe kann von Windows nicht installiert werden, da es von einem Framework abhängig ist, das nicht gefunden wurde. Stellen Sie das von CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US veröffentlichte Framework Microsoft.Services.Store.Engagement mit einer neutralen oder x64-Prozessorarchitektur und Mindestversion 10.0.1610.0 zusammen mit dem zu installierenden Paket bereit. Die derzeit installierten Frameworks mit dem Namen Microsoft.Services.Store.Engagement sind: {}
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 511
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 264
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 275
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 83

**Comment by Rayth** [comment]
Lite windows version? No microsoft/windows store?

**Comment by Pepsyah** [comment]
i have microsoft store

**Comment by Rayth** [comment]
try installing mc from the store, run it once, uninstall it then use the launcher
