### ISSUE TITLE
why delete all uwpapp‘s config  and no warn？

### ISSUE THREAD

**Issue by QianYI-Yan** [BedrockLauncher/BedrockLauncher#473]
Why did delete all the configuration files of my UWP app without backing up or transferring to a new directory? Didn't warn me that this would deltete all the profiles of my UWP app

**Comment by Rayth** [comment]
what configs are you referring to?

**Comment by QianYI-Yan** [comment]
> 你指的是什么配置？

AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang

**Comment by Rayth** [comment]
The first time you run the launcher, the folder gets backed up to a "RecoveryData" installation inside the launcher. goto the installations tab on the launcher.

**Comment by QianYI-Yan** [comment]
> 首次运行启动器时，该文件夹将备份到启动器内的“RecoveryData”安装中。转到启动器上的“安装”选项卡。

I only got an error when I started

System.IO.FileNotFoundException: Unable to find the specified file.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.Management.Core.IApplicationDataManagerStaticsMethods.CreateForPackageFamily(IObjectReference _obj, String packageFamilyName)
   at Windows.Management.Core.ApplicationDataManager.CreateForPackageFamily(String packageFamilyName)
   at BedrockLauncher.Handlers.BackupHandler.<>c__DisplayClass3_0.<<BackupData>b__0>d.MoveNext() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\BackupHandler.cs:line 51

**Comment by QianYI-Yan** [comment]
> 首次运行启动器时，该文件夹将备份到启动器内的“RecoveryData”安装中。转到启动器上的“安装”选项卡。

The good thing is that 360 can recover some of the important files (server list
