### ISSUE TITLE
Opening the “…” version menu lags and crashes the program.

### ISSUE THREAD

**Issue by kijeEnki** [BedrockLauncher/BedrockLauncher#477]
title

**Comment by Rayth** [comment]
Can you upload a log file. Located in the `app/data/logs` folder from where you ran startbedrocklauncher.exe from

**Comment by kijeEnki** [comment]
```
2024-07-04 20:11:16.2164|DEBUG||Version: 2024.5.31.2
2024-07-04 20:11:16.3134|DEBUG||Git Repo: https://github.com/BedrockLauncher/BedrockLauncher
2024-07-04 20:11:16.3134|DEBUG||Git Branch: lite
2024-07-04 20:11:16.3134|DEBUG||Git Commit: 660a061
2024-07-04 20:11:16.3134|DEBUG||Git Sha: 660a0612a88faec1823e719a9ef7d5d02f888e3f
2024-07-04 20:11:16.3745|DEBUG||Application Starting...
2024-07-04 20:11:18.4415|DEBUG||Application Initalization Started!
2024-07-04 20:11:18.4415|DEBUG||Application Initalization Finished!
2024-07-04 20:11:24.5694|DEBUG||Preparing Application...
2024-07-04 20:13:42.4158|DEBUG||UpdateDBFromStore.UpdateDB Failed!
2024-07-04 20:13:42.4158|DEBUG||File: C:\Users\Дмитрий\AppData\Roaming\.minecraft_bedrock\winstore_technical_versions.txt
2024-07-04 20:13:42.4158|DEBUG||isBeta: Preview
2024-07-04 20:13:42.7340|DEBUG||System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.doHttpRequest(String url, String data) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 254
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.fetchCookie(String configLastChanged, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 297
   at BedrockLauncher.UpdateProcessor.Handlers.VersionManager.<>c__DisplayClass16_0.<<UpdateDBFromStore>g__UpdateDB|0>d.MoveNext() in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\VersionManager.cs:line 166
2024-07-04 20:13:55.6208|DEBUG||Checking for updates
2024-07-04 20:13:56.8279|DEBUG||Current tag: 2024.5.31.2
2024-07-04 20:13:56.8279|DEBUG||Latest tag: 2024.5.31.2
2024-07-04 20:13:56.8279|DEBUG||Preparing Application: DONE
```

**Comment by Rayth** [comment]
disable the option to get latest version from store then restart the launcher and try

**Comment by kijeEnki** [comment]
Nope, didn’t work

**Comment by Rayth** [comment]
under `%appdata%\.minecraft_bedrock` do you have a file called winstore_technical_versions.txt? if so try delete it

**Comment by kijeEnki** [comment]
Nope, it still loads for a little bit and then lags forever. :(

**Comment by Rayth** [comment]
can you upload your settings.json file from that same location
