### ISSUE TITLE
ERROR: App registration failed ( Please try again :( )

### ISSUE THREAD

**Issue by vaclavec** [BedrockLauncher/BedrockLauncher#486]
**Minecraft can not be launched**

**content of the window shown:**

BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Windows cannot install package Microsoft.MinecraftWindowsBeta_1.21.2024.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install.
 ---> System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftWindowsBeta_1.21.2024.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install.
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 511
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 264
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 275
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 83
   
**View crash report won′t open log file**
**BedrockLauncher is in Portable mode**
**Windows version 10.0.26100.1297**

**Same behavior is also observed with other Bedrock versions**

Possible solution: Installing this .appx Package to register the game for it to open
[https://github.com/mcrax/mcrev/blob/master/Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe.Appx](url)

**Comment by Rayth** [comment]
We're already aware of this possible solution and use it on the discord already.
