### ISSUE TITLE
Crash after clicking "Install" on a peview

### ISSUE THREAD

**Issue by Sas-0** [BedrockLauncher/BedrockLauncher#489]
When i create a new beta or preview installation it just doesnt work. It opens the installed preview but when i click install it gives me an error saying download failed.

**Comment by Rayth** [comment]
Beta's will not work (in fact they should be removed)

Regarding previews, exactly which preview version are you trying to install? What error are you getting?

**Comment by Sas-0** [comment]
Any version before 1.21.20.21 (Preview) it just stops working. Here what it gives me after clicking install on 1.21.10.24 preview:



BedrockLauncher.Exceptions.PackageDownloadFailedException: Failed to Find Download Links
 ---> System.Exception: Failed to Find Download Links
 ---> System.Exception: first_node_or_throw
 ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at BedrockLauncher.UpdateProcessor.Extensions.NetworkExtensions.first_node_or_throw(XElement element, XName name) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Extensions\NetworkExtensions.cs:line 50
   --- End of inner exception stack trace ---
   at BedrockLauncher.UpdateProcessor.Extensions.NetworkExtensions.first_node_or_throw(XElement element, XName name) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Extensions\NetworkExtensions.cs:line 55
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.getDownloadLinks(String updateIdentity, Int32 revisionNumber, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 357
   --- End of inner exception stack trace ---
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.getDownloadLinks(String updateIdentity, Int32 revisionNumber, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 370
   at BedrockLauncher.UpdateProcessor.Handlers.StoreNetwork.getDownloadLink(String updateIdentity, Int32 revisionNumber, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\StoreNetwork.cs:line 376
   at BedrockLauncher.UpdateProcessor.Handlers.VersionManager.DownloadVersion(String versionName, String updateIdentity, Int32 revisionNumber, String destination, DownloadProgress progress, CancellationToken cancellationToken, VersionType type) in D:\a\BedrockLauncher\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Handlers\VersionManager.cs:line 49
   at BedrockLauncher.Downloaders.VersionDownloader.DownloadVersion(String versionName, String packageID, Int32 revisionNumber, String destination, DownloadProgress progress, CancellationToken cancellationToken, VersionType versionType) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 44
   at BedrockLauncher.Handlers.PackageHandler.DownloadPackage(MCVersion v, String dlPath, CancellationTokenSource cancelSource) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 234
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.DownloadAndExtractPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 212
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 80

**Comment by Rayth** [comment]
Microsoft periodically remove old previews from the store making them unavailable unless you already installed them via the launcher. For this reason, we've now started deleting old previews from the version list, but sometimes clients dont replace the whole version list and just add to it when new stuff gets added. There's nothing we can do about this.

**Comment by Sas-0** [comment]
I understand.
