### ISSUE TITLE
[BUG] Minecraft Pocket edition 1.1.5.0 Doesn't start, log Below

### ISSUE THREAD

**Issue by NoNameRN12** [BedrockLauncher/BedrockLauncher#528]
BedrockLauncher.Exceptions.PackageProcessHookFailedException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at BedrockLauncher.Handlers.PackageHandler.<>c__DisplayClass27_0.<UpdatePackageHandle>b__0() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 466
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.<>c__DisplayClass27_0.<UpdatePackageHandle>b__0() in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 482
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at BedrockLauncher.Handlers.PackageHandler.UpdatePackageHandle(AppActivationResult app) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 462
   at BedrockLauncher.Handlers.PackageHandler.LaunchPackage(MCVersion v, String dirPath, Boolean KeepLauncherOpen) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 59

**Comment by Rayth** [comment]
This is not a launcher error. This means the game crashed as soon as it launched so the Launcher couldn't see the object of the game.
![image](https://github.com/user-attachments/assets/90d755a7-845a-4614-8f5f-834f6f399c94)

**Comment by NoNameRN12** [comment]
> This is not a launcher error. This means the game crashed as soon as it launched so the Launcher couldn't see the object of the game. ![image](https://private-user-images.githubusercontent.com/4260473/365441104-90d755a7-845a-4614-8f5f-834f6f399c94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MDI0NTUsIm5iZiI6MTcyNTgwMjE1NSwicGF0aCI6Ii80MjYwNDczLzM2NTQ0MTEwNC05MGQ3NTVhNy04NDVhLTQ2MTQtOGY1Zi04MzRmNmYzOTljOTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDhUMTMyOTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGY3NDg4ZTNjY2M0MTMyZjk3MzRiZDhmYzIxOWQzNTg1Nzk0NTMxMzQ1ZDNjMTJjYWJhMDAzNmI5ZDEzM2QxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aBo-JjDtyXYe-kXA85pbT477vl0XEXkteUZoAz319hw)

So if so, but is it possible to fix this somehow?

**Comment by Rayth** [comment]
Find out why your computer crashed the game. Nothing to do with us.
