### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Darknife339** [BedrockLauncher/BedrockLauncher#554]
I can't install minecraft bedrock 21.40.3, it says:
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.21.4003.0_x64__8wekyb3d8bbwe because it depends on a framework that cannot be found. Please provide the framework "Microsoft.VCLibs.140.00" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" with neutral or x64 processor architecture and minimum version 14.0.33519.0 along with this package for installation. Platforms named 'Microsoft.VCLibs.140.00' currently installed: {Microsoft.VCLibs.140.00_14.0.30704.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.32530.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.32530.0_x64__8wekyb3d8bbwe}
---> System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.21.4003.0_x64__8wekyb3d8bbwe because it depends on a platform that cannot be found. Please provide the platform "Microsoft.VCLibs.140.00" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" with neutral or x64 processor architecture and minimum version 14.0.33519.0 with this package for installation. Platforms named "Microsoft.VCLibs.140.00" currently installed: {Microsoft.VCLibs.140.00_14.0.30704.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.32530.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.32530.0_x64__8wekyb3d8bbwe}
at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 535
at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 280
 --- End of inner exception stack trace ---
 at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 291
 at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher\Handlers\PackageHandler.cs:line 84
![изображение](https://github.com/user-attachments/assets/4ca2072b-f23b-4f56-a8c4-6ab7d448eb94)

**Comment by Rayth** [comment]
go get your microsoft store fixed first then try. Any further support please join discord
