### ISSUE TITLE
`PreserveApplicationData` blocks previously installed Minecraft from being uninstalled

### ISSUE THREAD

**Issue by FireDragonboy** [BedrockLauncher/BedrockLauncher#76]
Error log on first time startup:
```
Application Starting...
Checking for updates
Current tag: 0.0.2.6
Latest tag: 0.0.2.1
Application Pre-Initalization Finished!
Moving backup Minecraft data to: C:\Users\Bandana\AppData\Roaming\.minecraft_bedrock\installations\Fire Dragon\RecoveryData_3\packageData
Download start
Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/8d4b5b4e-ed71-4465-9a5f-6e938b3015fb?P1=1632419872&P2=404&P3=2&P4=Gyko2VThOYnJpYKMDFV1ayXggjutx5j97xGWRMYoaW7V0F9uINNAsEbzQdCokDJx%2f5MT19hT7uh7wVomaa1qog%3d%3d
Actual download started
Download complete
Extraction started
System.Windows.Threading.DispatcherUnhandledExceptionEventArgs
Extracted successfully
Removing package: Microsoft.MinecraftUWP_1.17.1101.0_x64__8wekyb3d8bbwe
Deployment failed: Windows cannot remove Microsoft.MinecraftUWP_1.17.1101.0_x64__8wekyb3d8bbwe because the PreserveApplicationData flag can only be used on a package that was deployed in development mode.
App launch failed:
System.Exception: Deployment failed: Windows cannot remove Microsoft.MinecraftUWP_1.17.1101.0_x64__8wekyb3d8bbwe because the PreserveApplicationData flag can only be used on a package that was deployed in development mode.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 575
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<UnregisterPackages>d__26.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 525
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<Launch>d__19.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 276
```

**Comment by CarJem** [comment]
Now this is the first good issue in attempting to fix issue #39
