### ISSUE TITLE
Failed to find download links

### ISSUE THREAD

**Issue by Rayth** [BedrockLauncher/BedrockLauncher#81]
Just encountered this bug. Version 0.2.6

```
System.Exception: Failed to Find Download Links ---> System.InvalidOperationException: Sequence contains no matching element
   at BedrockLauncher.UpdateProcessor.Win10VersionDBExtensions.first_node_or_throw(XElement element, XName name) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBExtensions.cs:line 55
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 426
   --- End of inner exception stack trace ---
   at BedrockLauncher.ViewModels.GameManager.<DownloadVersion>d__21.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by njt1982** [comment]
Getting the same error too...

```
System.Exception: Failed to Find Download Links ---> System.InvalidOperationException: Sequence contains no matching element
   at BedrockLauncher.UpdateProcessor.Win10VersionDBExtensions.first_node_or_throw(XElement element, XName name) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBExtensions.cs:line 55
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 426
   --- End of inner exception stack trace ---
   at BedrockLauncher.ViewModels.GameManager.<DownloadVersion>d__21.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<Download>d__20.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 334
```

The interesting part of that path is that I dont have a D Drive ;)

**Comment by Hedwig7s** [comment]
That's alot of mentions
Any progress to a fix?

**Comment by Rayth** [comment]
> That's alot of mentions Any progress to a fix?

the whole launcher is currently undergoing re-construction which will hopefully fix.

**Comment by Hedwig7s** [comment]
> > That's alot of mentions Any progress to a fix?
> 
> the whole launcher is currently undergoing re-construction which will hopefully fix.

I hope so as it's downloading previews as releases then failing to launch them (with no error)
Any way to try "Experimental/Canary" builds of the launcher (more unstable than beta)?

**Comment by Rayth** [comment]
> Actually @Rayth Can I talk to you privately? If so how?

I'm on the discord.
