### ISSUE TITLE
Can't download any versions

### ISSUE THREAD

**Issue by DUCKONAROLL** [BedrockLauncher/BedrockLauncher#82]
Whenever I try to download any version at all, I keep getting error code -2146233088 and the following error:

```
System.Exception: Failed to Find Download Links ---> System.InvalidOperationException: Sequence contains no matching element
   at BedrockLauncher.UpdateProcessor.Win10VersionDBExtensions.first_node_or_throw(XElement element, XName name) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBExtensions.cs:line 55
   at BedrockLauncher.UpdateProcessor.Win10StoreNetwork.<getDownloadLinks>d__32.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10StoreNetwork.cs:line 426
   --- End of inner exception stack trace ---
   at BedrockLauncher.ViewModels.GameManager.<DownloadVersion>d__21.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 386
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<Download>d__20.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 334
```

**Comment by TresAbhi** [comment]
Duplicated of #81
