### ISSUE TITLE
Launcher fails to access `AppxManifest.xml`

### ISSUE THREAD

**Issue by NT690** [BedrockLauncher/BedrockLauncher#85]
Error :

```
Application Starting...
Checking for updates
Current tag: 0.0.2.6
Latest tag: 0.0.2.6
Application Pre-Initalization Finished!
Registering package
Deployment failed: error 0x80070002: Opening file from location: AppxManifest.xml failed with error: The system cannot find the file specified.
.
App re-register failed:
System.Exception: Deployment failed: error 0x80070002: Opening file from location: AppxManifest.xml failed with error: The system cannot find the file specified.
.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<DeploymentProgressWrapper>d__28.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 575
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<RegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 540
App launch failed:
System.Exception: Deployment failed: error 0x80070002: Opening file from location: AppxManifest.xml failed with error: The system cannot find the file specified.
.
   at BedrockLauncher.ViewModels.GameManager.<RegisterPackage>d__27.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 549
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<Launch>d__19.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 277
```

**Comment by NT690** [comment]
ms store doesn't open properly and wsreset.exe, `Add-AppxPackage -DisableDevelopmentMode -Register $Env:SystemRoot\WinStore\AppxManifest.XML` in Powershell returns the error `Add-AppxPackage : Cannot find path 'C:\WINDOWS\WinStore\AppxManifest.XML' because it does not exist.
At line:1 char:1
 Add-AppxPackage -DisableDevelopmentMode -Register $Env:SystemRoot\Win ...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : ObjectNotFound: (C:\WINDOWS\WinStore\AppxManifest.XML:String) [Add-AppxPackage], ItemNot
   FoundException
     FullyQualifiedErrorId : PathNotFound,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand`
