### ISSUE TITLE
Launcher fails to access files

### ISSUE THREAD

**Issue by standojacat** [BedrockLauncher/BedrockLauncher#97]
Application Starting...
Checking for updates
Current tag: 0.0.2.6
Latest tag: 0.0.2.1
Version list technical cache load failed:
System.IO.FileNotFoundException: Could not find file 'C:\Users\Usernamecensored\Downloads\build\data\technical_local_versions.txt'.
File name: 'C:\Users\Usernamecensored\Downloads\build\data\technical_local_versions.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionTextDb.Read(String filePath) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:line 51
   at BedrockLauncher.Downloaders.VersionDownloader.LoadFromTechCache() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 158
Application Pre-Initalization Finished!
Version list local cache load failed:
System.IO.FileNotFoundException: Could not find file 'C:\Users\Usernamecensored\Downloads\build\.minecraft_bedrock\versions.json'.
File name: 'C:\Users\Usernamecensored\Downloads\build\.minecraft_bedrock\versions.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionJsonDb.ReadJson(String filePath) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:line 134
   at BedrockLauncher.Downloaders.VersionDownloader.LoadFromLocalCache(ObservableCollection`1 versions) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 137
Version list user cache load failed:
System.IO.FileNotFoundException: Could not find file 'C:\Users\Usernamecensored\Downloads\build\.minecraft_bedrock\local_versions.json'.
File name: 'C:\Users\Usernamecensored\Downloads\build\.minecraft_bedrock\local_versions.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionJsonDb.ReadJson(String filePath) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:line 134
   at BedrockLauncher.Downloaders.VersionDownloader.LoadFromUserCache(ObservableCollection`1 versions) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 116
Version list user cache load failed:
System.IO.FileNotFoundException: Could not find file 'C:\Users\Usernamecensored\Downloads\build\.minecraft_bedrock\local_versions.json'.
File name: 'C:\Users\Usernamecensored\Downloads\build\.minecraft_bedrock\local_versions.json'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionJsonDb.ReadJson(String filePath) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:line 134
   at BedrockLauncher.Downloaders.VersionDownloader.LoadFromUserCache(ObservableCollection`1 versions) in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 116
Version list technical cache load failed:
System.IO.FileNotFoundException: Could not find file 'C:\Users\Usernamecensored\Downloads\build\.minecraft_bedrock\technical_local_versions.txt'.
File name: 'C:\Users\Usernamecensored\Downloads\build\.minecraft_bedrock\technical_local_versions.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at BedrockLauncher.UpdateProcessor.Win10VersionDBManager.Win10VersionTextDb.Read(String filePath) in D:\UserData\Source\mc_repos\BedrockLauncher\modules\BedrockLauncher.UpdateProcessor\Win10VersionDBManager.cs:line 51
   at BedrockLauncher.Downloaders.VersionDownloader.LoadFromTechCache() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\Downloaders\VersionDownloader.cs:line 158
Download start
Waiting for authentication
Authentication complete
Resolved download link: Download link censored
Actual download started
Download complete
Extraction started
Extracted successfully
App launch failed:
System.IO.IOException: Access to the path 'C:\Users\Usernamecensored\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang' is denied.
   at BedrockLauncher.ViewModels.GameManager.<>c__DisplayClass23_0.<SetInstallationDataPath>b__0() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 462
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<SetInstallationDataPath>d__23.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 407
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BedrockLauncher.ViewModels.GameManager.<Launch>d__19.MoveNext() in D:\UserData\Source\mc_repos\BedrockLauncher\BedrockLauncher\ViewModels\GameManager.cs:line 275

**Comment by standojacat** [comment]
I am running the application as admin
